package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Eh03tnif;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Eh03tnifExample;
import org.apache.ibatis.annotations.Param;

public interface Eh03tnifMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.EH03TNIF
     *
     * @mbggenerated Mon Sep 15 11:01:57 ICT 2014
     */
    int countByExample(Eh03tnifExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.EH03TNIF
     *
     * @mbggenerated Mon Sep 15 11:01:57 ICT 2014
     */
    int deleteByExample(Eh03tnifExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.EH03TNIF
     *
     * @mbggenerated Mon Sep 15 11:01:57 ICT 2014
     */
    int insert(Eh03tnif record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.EH03TNIF
     *
     * @mbggenerated Mon Sep 15 11:01:57 ICT 2014
     */
    int insertSelective(Eh03tnif record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.EH03TNIF
     *
     * @mbggenerated Mon Sep 15 11:01:57 ICT 2014
     */
    List<Eh03tnif> selectByExample(Eh03tnifExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.EH03TNIF
     *
     * @mbggenerated Mon Sep 15 11:01:57 ICT 2014
     */
    int updateByExampleSelective(@Param("record") Eh03tnif record, @Param("example") Eh03tnifExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.EH03TNIF
     *
     * @mbggenerated Mon Sep 15 11:01:57 ICT 2014
     */
    int updateByExample(@Param("record") Eh03tnif record, @Param("example") Eh03tnifExample example);
}