package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Em34tbbn;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Em34tbbnExample;
import org.apache.ibatis.annotations.Param;

public interface Em34tbbnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EM34TBBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(Em34tbbnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EM34TBBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(Em34tbbnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EM34TBBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(Em34tbbn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EM34TBBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(Em34tbbn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EM34TBBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<Em34tbbn> selectByExample(Em34tbbnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EM34TBBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") Em34tbbn record, @Param("example") Em34tbbnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EM34TBBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") Em34tbbn record, @Param("example") Em34tbbnExample example);
}