package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Em40esdl;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Em40esdlExample;
import org.apache.ibatis.annotations.Param;

public interface Em40esdlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EM40ESDL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(Em40esdlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EM40ESDL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(Em40esdlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EM40ESDL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(Em40esdl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EM40ESDL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(Em40esdl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EM40ESDL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<Em40esdl> selectByExample(Em40esdlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EM40ESDL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") Em40esdl record, @Param("example") Em40esdlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EM40ESDL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") Em40esdl record, @Param("example") Em40esdlExample example);
}