package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Eobpstbl;
import jp.co.necsoft.web_md.core.common.mybatis.dto.EobpstblExample;
import org.apache.ibatis.annotations.Param;

public interface EobpstblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EOBPSTBL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(EobpstblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EOBPSTBL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(EobpstblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EOBPSTBL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(Eobpstbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EOBPSTBL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(Eobpstbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EOBPSTBL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<Eobpstbl> selectByExample(EobpstblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EOBPSTBL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") Eobpstbl record, @Param("example") EobpstblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.EOBPSTBL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") Eobpstbl record, @Param("example") EobpstblExample example);
}