package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.F002krui;
import jp.co.necsoft.web_md.core.common.mybatis.dto.F002kruiExample;
import org.apache.ibatis.annotations.Param;

public interface F002kruiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.F002KRUI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(F002kruiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.F002KRUI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(F002kruiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.F002KRUI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(F002krui record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.F002KRUI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(F002krui record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.F002KRUI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<F002krui> selectByExample(F002kruiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.F002KRUI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") F002krui record, @Param("example") F002kruiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.F002KRUI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") F002krui record, @Param("example") F002kruiExample example);
}