package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.F009simd;
import jp.co.necsoft.web_md.core.common.mybatis.dto.F009simdExample;
import org.apache.ibatis.annotations.Param;

public interface F009simdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.F009SIMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(F009simdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.F009SIMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(F009simdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.F009SIMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(F009simd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.F009SIMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(F009simd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.F009SIMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<F009simd> selectByExample(F009simdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.F009SIMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") F009simd record, @Param("example") F009simdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.F009SIMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") F009simd record, @Param("example") F009simdExample example);
}