package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H001Orderbook;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H001OrderbookExample;
import org.apache.ibatis.annotations.Param;

public interface H001OrderbookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H001_ORDERBOOK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(H001OrderbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H001_ORDERBOOK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(H001OrderbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H001_ORDERBOOK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(H001Orderbook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H001_ORDERBOOK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(H001Orderbook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H001_ORDERBOOK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<H001Orderbook> selectByExample(H001OrderbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H001_ORDERBOOK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") H001Orderbook record, @Param("example") H001OrderbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H001_ORDERBOOK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") H001Orderbook record, @Param("example") H001OrderbookExample example);
}