package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H030sinh;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H030sinhExample;
import org.apache.ibatis.annotations.Param;

public interface H030sinhMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H030SINH
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(H030sinhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H030SINH
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(H030sinhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H030SINH
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(H030sinh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H030SINH
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(H030sinh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H030SINH
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<H030sinh> selectByExample(H030sinhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H030SINH
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") H030sinh record, @Param("example") H030sinhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H030SINH
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") H030sinh record, @Param("example") H030sinhExample example);
}