package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H050hatp;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H050hatpExample;
import org.apache.ibatis.annotations.Param;

public interface H050hatpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(H050hatpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(H050hatpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(H050hatp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(H050hatp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<H050hatp> selectByExample(H050hatpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") H050hatp record, @Param("example") H050hatpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") H050hatp record, @Param("example") H050hatpExample example);
}