package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H060hctl;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H060hctlExample;
import org.apache.ibatis.annotations.Param;

public interface H060hctlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H060HCTL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(H060hctlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H060HCTL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(H060hctlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H060HCTL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(H060hctl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H060HCTL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(H060hctl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H060HCTL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<H060hctl> selectByExample(H060hctlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H060HCTL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") H060hctl record, @Param("example") H060hctlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H060HCTL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") H060hctl record, @Param("example") H060hctlExample example);
}