package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H150sjko;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H150sjkoExample;
import org.apache.ibatis.annotations.Param;

public interface H150sjkoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H150SJKO
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int countByExample(H150sjkoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H150SJKO
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int deleteByExample(H150sjkoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H150SJKO
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int insert(H150sjko record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H150SJKO
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int insertSelective(H150sjko record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H150SJKO
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    List<H150sjko> selectByExample(H150sjkoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H150SJKO
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int updateByExampleSelective(@Param("record") H150sjko record, @Param("example") H150sjkoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H150SJKO
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int updateByExample(@Param("record") H150sjko record, @Param("example") H150sjkoExample example);
}