package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H170sant;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H170santExample;
import org.apache.ibatis.annotations.Param;

public interface H170santMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H170SANT
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int countByExample(H170santExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H170SANT
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int deleteByExample(H170santExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H170SANT
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int insert(H170sant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H170SANT
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int insertSelective(H170sant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H170SANT
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    List<H170sant> selectByExample(H170santExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H170SANT
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int updateByExampleSelective(@Param("record") H170sant record, @Param("example") H170santExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H170SANT
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int updateByExample(@Param("record") H170sant record, @Param("example") H170santExample example);
}