package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H200sant;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H200santExample;
import org.apache.ibatis.annotations.Param;

public interface H200santMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H200SANT
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int countByExample(H200santExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H200SANT
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int deleteByExample(H200santExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H200SANT
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int insert(H200sant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H200SANT
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int insertSelective(H200sant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H200SANT
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    List<H200sant> selectByExample(H200santExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H200SANT
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int updateByExampleSelective(@Param("record") H200sant record, @Param("example") H200santExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H200SANT
     *
     * @mbggenerated Mon Jun 08 13:53:13 ICT 2015
     */
    int updateByExample(@Param("record") H200sant record, @Param("example") H200santExample example);
}