package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H610hcls;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H610hclsExample;
import org.apache.ibatis.annotations.Param;

public interface H610hclsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H610HCLS
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(H610hclsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H610HCLS
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(H610hclsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H610HCLS
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(H610hcls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H610HCLS
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(H610hcls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H610HCLS
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<H610hcls> selectByExample(H610hclsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H610HCLS
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") H610hcls record, @Param("example") H610hclsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H610HCLS
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") H610hcls record, @Param("example") H610hclsExample example);
}