package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H701kzin;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H701kzinExample;
import org.apache.ibatis.annotations.Param;

public interface H701kzinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H701KZIN
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(H701kzinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H701KZIN
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(H701kzinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H701KZIN
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(H701kzin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H701KZIN
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(H701kzin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H701KZIN
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<H701kzin> selectByExample(H701kzinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H701KZIN
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") H701kzin record, @Param("example") H701kzinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H701KZIN
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") H701kzin record, @Param("example") H701kzinExample example);
}