package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H701ohat;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H701ohatExample;
import org.apache.ibatis.annotations.Param;

public interface H701ohatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H701OHAT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(H701ohatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H701OHAT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(H701ohatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H701OHAT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(H701ohat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H701OHAT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(H701ohat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H701OHAT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<H701ohat> selectByExample(H701ohatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H701OHAT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") H701ohat record, @Param("example") H701ohatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H701OHAT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") H701ohat record, @Param("example") H701ohatExample example);
}