package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H702lhat;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H702lhatExample;
import org.apache.ibatis.annotations.Param;

public interface H702lhatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H702LHAT
     *
     * @mbggenerated Tue Jun 02 16:10:58 ICT 2015
     */
    int countByExample(H702lhatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H702LHAT
     *
     * @mbggenerated Tue Jun 02 16:10:58 ICT 2015
     */
    int deleteByExample(H702lhatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H702LHAT
     *
     * @mbggenerated Tue Jun 02 16:10:58 ICT 2015
     */
    int insert(H702lhat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H702LHAT
     *
     * @mbggenerated Tue Jun 02 16:10:58 ICT 2015
     */
    int insertSelective(H702lhat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H702LHAT
     *
     * @mbggenerated Tue Jun 02 16:10:58 ICT 2015
     */
    List<H702lhat> selectByExample(H702lhatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H702LHAT
     *
     * @mbggenerated Tue Jun 02 16:10:58 ICT 2015
     */
    int updateByExampleSelective(@Param("record") H702lhat record, @Param("example") H702lhatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H702LHAT
     *
     * @mbggenerated Tue Jun 02 16:10:58 ICT 2015
     */
    int updateByExample(@Param("record") H702lhat record, @Param("example") H702lhatExample example);
}