package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H703lhat;
import jp.co.necsoft.web_md.core.common.mybatis.dto.H703lhatExample;
import org.apache.ibatis.annotations.Param;

public interface H703lhatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H703LHAT
     *
     * @mbggenerated Tue Jun 02 16:11:14 ICT 2015
     */
    int countByExample(H703lhatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H703LHAT
     *
     * @mbggenerated Tue Jun 02 16:11:14 ICT 2015
     */
    int deleteByExample(H703lhatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H703LHAT
     *
     * @mbggenerated Tue Jun 02 16:11:14 ICT 2015
     */
    int insert(H703lhat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H703LHAT
     *
     * @mbggenerated Tue Jun 02 16:11:14 ICT 2015
     */
    int insertSelective(H703lhat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H703LHAT
     *
     * @mbggenerated Tue Jun 02 16:11:14 ICT 2015
     */
    List<H703lhat> selectByExample(H703lhatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H703LHAT
     *
     * @mbggenerated Tue Jun 02 16:11:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") H703lhat record, @Param("example") H703lhatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H703LHAT
     *
     * @mbggenerated Tue Jun 02 16:11:14 ICT 2015
     */
    int updateByExample(@Param("record") H703lhat record, @Param("example") H703lhatExample example);
}