package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.K007gekk;
import jp.co.necsoft.web_md.core.common.mybatis.dto.K007gekkExample;
import org.apache.ibatis.annotations.Param;

public interface K007gekkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K007GEKK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(K007gekkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K007GEKK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(K007gekkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K007GEKK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(K007gekk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K007GEKK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(K007gekk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K007GEKK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<K007gekk> selectByExample(K007gekkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K007GEKK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") K007gekk record, @Param("example") K007gekkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K007GEKK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") K007gekk record, @Param("example") K007gekkExample example);
}