package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.K009simd;
import jp.co.necsoft.web_md.core.common.mybatis.dto.K009simdExample;
import org.apache.ibatis.annotations.Param;

public interface K009simdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K009SIMD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(K009simdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K009SIMD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(K009simdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K009SIMD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(K009simd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K009SIMD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(K009simd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K009SIMD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<K009simd> selectByExample(K009simdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K009SIMD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") K009simd record, @Param("example") K009simdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K009SIMD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") K009simd record, @Param("example") K009simdExample example);
}