package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.K012rinf;
import jp.co.necsoft.web_md.core.common.mybatis.dto.K012rinfExample;
import org.apache.ibatis.annotations.Param;

public interface K012rinfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K012RINF
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(K012rinfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K012RINF
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(K012rinfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K012RINF
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(K012rinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K012RINF
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(K012rinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K012RINF
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<K012rinf> selectByExample(K012rinfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K012RINF
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") K012rinf record, @Param("example") K012rinfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K012RINF
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") K012rinf record, @Param("example") K012rinfExample example);
}