package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.K113ssen;
import jp.co.necsoft.web_md.core.common.mybatis.dto.K113ssenExample;
import org.apache.ibatis.annotations.Param;

public interface K113ssenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K113SSEN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(K113ssenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K113SSEN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(K113ssenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K113SSEN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(K113ssen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K113SSEN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(K113ssen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K113SSEN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<K113ssen> selectByExample(K113ssenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K113SSEN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") K113ssen record, @Param("example") K113ssenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.K113SSEN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") K113ssen record, @Param("example") K113ssenExample example);
}