package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;

import jp.co.necsoft.web_md.core.common.mybatis.dto.CodeMaster;
import jp.co.necsoft.web_md.core.common.mybatis.dto.CodeName;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M002dbum;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M002dbumExample;
import org.apache.ibatis.annotations.Param;

public interface M002dbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M002DBUM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(M002dbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M002DBUM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(M002dbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M002DBUM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(M002dbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M002DBUM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(M002dbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M002DBUM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<M002dbum> selectByExample(M002dbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M002DBUM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") M002dbum record, @Param("example") M002dbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M002DBUM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") M002dbum record, @Param("example") M002dbumExample example);

    /**
     *
     */
    List<CodeName> selectCodeNameByExample(M002dbumExample example);

    /**
     *
     */
    List<CodeMaster> selectCodeMaterByExample(M002dbumExample example);
}