package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;

import jp.co.necsoft.web_md.core.common.mybatis.dto.CodeMaster;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M007kijm;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M007kijmExample;
import org.apache.ibatis.annotations.Param;

public interface M007kijmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M007KIJM
     *
     * @mbggenerated Tue Jun 09 13:36:15 ICT 2015
     */
    int countByExample(M007kijmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M007KIJM
     *
     * @mbggenerated Tue Jun 09 13:36:15 ICT 2015
     */
    int deleteByExample(M007kijmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M007KIJM
     *
     * @mbggenerated Tue Jun 09 13:36:15 ICT 2015
     */
    int insert(M007kijm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M007KIJM
     *
     * @mbggenerated Tue Jun 09 13:36:15 ICT 2015
     */
    int insertSelective(M007kijm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M007KIJM
     *
     * @mbggenerated Tue Jun 09 13:36:15 ICT 2015
     */
    List<M007kijm> selectByExample(M007kijmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M007KIJM
     *
     * @mbggenerated Tue Jun 09 13:36:15 ICT 2015
     */
    int updateByExampleSelective(@Param("record") M007kijm record, @Param("example") M007kijmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M007KIJM
     *
     * @mbggenerated Tue Jun 09 13:36:15 ICT 2015
     */
    int updateByExample(@Param("record") M007kijm record, @Param("example") M007kijmExample example);

    List<CodeMaster> selectCodeMasterByExample(M007kijmExample example);
}