package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M008kijt;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M008kijtExample;
import org.apache.ibatis.annotations.Param;

public interface M008kijtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M008KIJT
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(M008kijtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M008KIJT
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(M008kijtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M008KIJT
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(M008kijt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M008KIJT
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(M008kijt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M008KIJT
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<M008kijt> selectByExample(M008kijtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M008KIJT
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") M008kijt record, @Param("example") M008kijtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M008KIJT
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") M008kijt record, @Param("example") M008kijtExample example);
}