package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M009eobm;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M009eobmExample;
import org.apache.ibatis.annotations.Param;

public interface M009eobmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M009EOBM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(M009eobmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M009EOBM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(M009eobmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M009EOBM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(M009eobm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M009EOBM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(M009eobm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M009EOBM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<M009eobm> selectByExample(M009eobmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M009EOBM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") M009eobm record, @Param("example") M009eobmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M009EOBM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") M009eobm record, @Param("example") M009eobmExample example);
}