package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M014trbi;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M014trbiExample;
import org.apache.ibatis.annotations.Param;

public interface M014trbiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M014TRBI
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(M014trbiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M014TRBI
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(M014trbiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M014TRBI
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(M014trbi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M014TRBI
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(M014trbi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M014TRBI
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<M014trbi> selectByExample(M014trbiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M014TRBI
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") M014trbi record, @Param("example") M014trbiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M014TRBI
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") M014trbi record, @Param("example") M014trbiExample example);
}