package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M021ctlm;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M021ctlmExample;
import org.apache.ibatis.annotations.Param;

public interface M021ctlmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M021CTLM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(M021ctlmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M021CTLM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(M021ctlmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M021CTLM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(M021ctlm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M021CTLM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(M021ctlm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M021CTLM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<M021ctlm> selectByExample(M021ctlmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M021CTLM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") M021ctlm record, @Param("example") M021ctlmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M021CTLM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") M021ctlm record, @Param("example") M021ctlmExample example);
}