package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import java.util.Map;

import jp.co.necsoft.web_md.core.common.mybatis.dto.M022sibn;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M022sibnExample;
import org.apache.ibatis.annotations.Param;

public interface M022sibnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M022SIBN
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(M022sibnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M022SIBN
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(M022sibnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M022SIBN
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(M022sibn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M022SIBN
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(M022sibn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M022SIBN
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<M022sibn> selectByExample(M022sibnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M022SIBN
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") M022sibn record, @Param("example") M022sibnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M022SIBN
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") M022sibn record, @Param("example") M022sibnExample example);
    
    /**
     * Get presentNo by SAIBAN_KBN, DEN_KBN, KAISYIA_CD, TEN_CD.<br>
     * Params {saibanKbn, denKbn, kaisyaCd, tenCd}
     * 
     * @param example
     * @return
     */
    String selectPresentNoByParams(Map<String, String> example);
    int updatePresentNoByParams(Map<String, String> example);
    M022sibn selectM022sibnByParams(Map<String, String> example);
    int updateM022sibnByParams(Map<String, String> example);
    
}