package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M700seth;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M700sethExample;
import org.apache.ibatis.annotations.Param;

public interface M700sethMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M700SETH
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(M700sethExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M700SETH
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(M700sethExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M700SETH
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(M700seth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M700SETH
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(M700seth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M700SETH
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<M700seth> selectByExample(M700sethExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M700SETH
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") M700seth record, @Param("example") M700sethExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M700SETH
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") M700seth record, @Param("example") M700sethExample example);
}