package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M704zkhm;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M704zkhmExample;
import org.apache.ibatis.annotations.Param;

public interface M704zkhmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M704ZKHM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(M704zkhmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M704ZKHM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(M704zkhmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M704ZKHM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(M704zkhm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M704ZKHM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(M704zkhm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M704ZKHM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<M704zkhm> selectByExample(M704zkhmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M704ZKHM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") M704zkhm record, @Param("example") M704zkhmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M704ZKHM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") M704zkhm record, @Param("example") M704zkhmExample example);
}