package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M705kpkk;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M705kpkkExample;
import org.apache.ibatis.annotations.Param;

public interface M705kpkkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M705KPKK
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(M705kpkkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M705KPKK
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(M705kpkkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M705KPKK
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(M705kpkk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M705KPKK
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(M705kpkk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M705KPKK
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<M705kpkk> selectByExample(M705kpkkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M705KPKK
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") M705kpkk record, @Param("example") M705kpkkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M705KPKK
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") M705kpkk record, @Param("example") M705kpkkExample example);
}