package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M707gbyr;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M707gbyrExample;
import org.apache.ibatis.annotations.Param;

public interface M707gbyrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M707GBYR
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(M707gbyrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M707GBYR
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(M707gbyrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M707GBYR
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(M707gbyr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M707GBYR
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(M707gbyr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M707GBYR
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<M707gbyr> selectByExample(M707gbyrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M707GBYR
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") M707gbyr record, @Param("example") M707gbyrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M707GBYR
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") M707gbyr record, @Param("example") M707gbyrExample example);
}