package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;

import jp.co.necsoft.web_md.core.common.mybatis.dto.CodeMaster;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M708dpkm;
import jp.co.necsoft.web_md.core.common.mybatis.dto.M708dpkmExample;

import org.apache.ibatis.annotations.Param;

public interface M708dpkmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M708DPKM
     *
     * @mbggenerated Mon Jun 22 17:36:33 ICT 2015
     */
    int countByExample(M708dpkmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M708DPKM
     *
     * @mbggenerated Mon Jun 22 17:36:33 ICT 2015
     */
    int deleteByExample(M708dpkmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M708DPKM
     *
     * @mbggenerated Mon Jun 22 17:36:33 ICT 2015
     */
    int insert(M708dpkm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M708DPKM
     *
     * @mbggenerated Mon Jun 22 17:36:33 ICT 2015
     */
    int insertSelective(M708dpkm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M708DPKM
     *
     * @mbggenerated Mon Jun 22 17:36:33 ICT 2015
     */
    List<M708dpkm> selectByExample(M708dpkmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M708DPKM
     *
     * @mbggenerated Mon Jun 22 17:36:33 ICT 2015
     */
    int updateByExampleSelective(@Param("record") M708dpkm record, @Param("example") M708dpkmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.M708DPKM
     *
     * @mbggenerated Mon Jun 22 17:36:33 ICT 2015
     */
    int updateByExample(@Param("record") M708dpkm record, @Param("example") M708dpkmExample example);
    
    /** FOR NEUVE */
    List<CodeMaster> selectCodeMasterByExample(M708dpkmExample example); 
    List<CodeMaster> selectCodeMasterByExample1(M708dpkmExample example); 
}