package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Ms001Kyuyo;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Ms001KyuyoExample;
import org.apache.ibatis.annotations.Param;

public interface Ms001KyuyoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS001_KYUYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(Ms001KyuyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS001_KYUYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(Ms001KyuyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS001_KYUYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(Ms001Kyuyo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS001_KYUYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(Ms001Kyuyo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS001_KYUYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<Ms001Kyuyo> selectByExample(Ms001KyuyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS001_KYUYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") Ms001Kyuyo record, @Param("example") Ms001KyuyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS001_KYUYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") Ms001Kyuyo record, @Param("example") Ms001KyuyoExample example);
}