package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Ms002Mbusyo;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Ms002MbusyoExample;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Ms002MbusyoKey;
import org.apache.ibatis.annotations.Param;

public interface Ms002MbusyoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS002_MBUSYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(Ms002MbusyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS002_MBUSYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(Ms002MbusyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS002_MBUSYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByPrimaryKey(Ms002MbusyoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS002_MBUSYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(Ms002Mbusyo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS002_MBUSYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(Ms002Mbusyo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS002_MBUSYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<Ms002Mbusyo> selectByExample(Ms002MbusyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS002_MBUSYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    Ms002Mbusyo selectByPrimaryKey(Ms002MbusyoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS002_MBUSYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") Ms002Mbusyo record, @Param("example") Ms002MbusyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS002_MBUSYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") Ms002Mbusyo record, @Param("example") Ms002MbusyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS002_MBUSYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByPrimaryKeySelective(Ms002Mbusyo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.MS002_MBUSYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByPrimaryKey(Ms002Mbusyo record);
}