package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.N001kden;
import jp.co.necsoft.web_md.core.common.mybatis.dto.N001kdenExample;
import org.apache.ibatis.annotations.Param;

public interface N001kdenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N001KDEN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(N001kdenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N001KDEN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(N001kdenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N001KDEN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(N001kden record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N001KDEN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(N001kden record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N001KDEN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<N001kden> selectByExample(N001kdenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N001KDEN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") N001kden record, @Param("example") N001kdenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N001KDEN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") N001kden record, @Param("example") N001kdenExample example);
}