package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.N004rssi;
import jp.co.necsoft.web_md.core.common.mybatis.dto.N004rssiExample;
import org.apache.ibatis.annotations.Param;

public interface N004rssiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N004RSSI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(N004rssiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N004RSSI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(N004rssiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N004RSSI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(N004rssi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N004RSSI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(N004rssi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N004RSSI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<N004rssi> selectByExample(N004rssiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N004RSSI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") N004rssi record, @Param("example") N004rssiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N004RSSI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") N004rssi record, @Param("example") N004rssiExample example);
}