package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.N006ssan;
import jp.co.necsoft.web_md.core.common.mybatis.dto.N006ssanExample;
import org.apache.ibatis.annotations.Param;

public interface N006ssanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N006SSAN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(N006ssanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N006SSAN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(N006ssanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N006SSAN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(N006ssan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N006SSAN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(N006ssan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N006SSAN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<N006ssan> selectByExample(N006ssanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N006SSAN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") N006ssan record, @Param("example") N006ssanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.N006SSAN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") N006ssan record, @Param("example") N006ssanExample example);
}