package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.O004rssi;
import jp.co.necsoft.web_md.core.common.mybatis.dto.O004rssiExample;
import org.apache.ibatis.annotations.Param;

public interface O004rssiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.O004RSSI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(O004rssiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.O004RSSI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(O004rssiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.O004RSSI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(O004rssi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.O004RSSI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(O004rssi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.O004RSSI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<O004rssi> selectByExample(O004rssiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.O004RSSI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") O004rssi record, @Param("example") O004rssiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.O004RSSI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") O004rssi record, @Param("example") O004rssiExample example);
}