package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.O007gekk;
import jp.co.necsoft.web_md.core.common.mybatis.dto.O007gekkExample;
import org.apache.ibatis.annotations.Param;

public interface O007gekkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.O007GEKK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(O007gekkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.O007GEKK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(O007gekkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.O007GEKK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(O007gekk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.O007GEKK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(O007gekk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.O007GEKK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<O007gekk> selectByExample(O007gekkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.O007GEKK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") O007gekk record, @Param("example") O007gekkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.O007GEKK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") O007gekk record, @Param("example") O007gekkExample example);
}