package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S002tgkd;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S002tgkdExample;
import org.apache.ibatis.annotations.Param;

public interface S002tgkdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S002TGKD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(S002tgkdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S002TGKD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(S002tgkdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S002TGKD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(S002tgkd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S002TGKD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(S002tgkd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S002TGKD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<S002tgkd> selectByExample(S002tgkdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S002TGKD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") S002tgkd record, @Param("example") S002tgkdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S002TGKD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") S002tgkd record, @Param("example") S002tgkdExample example);
}