package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S003frid;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S003fridExample;
import org.apache.ibatis.annotations.Param;

public interface S003fridMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S003FRID
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(S003fridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S003FRID
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(S003fridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S003FRID
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(S003frid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S003FRID
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(S003frid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S003FRID
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<S003frid> selectByExample(S003fridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S003FRID
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") S003frid record, @Param("example") S003fridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S003FRID
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") S003frid record, @Param("example") S003fridExample example);
}