package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S006tgkt;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S006tgktExample;
import org.apache.ibatis.annotations.Param;

public interface S006tgktMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S006TGKT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(S006tgktExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S006TGKT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(S006tgktExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S006TGKT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(S006tgkt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S006TGKT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(S006tgkt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S006TGKT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<S006tgkt> selectByExample(S006tgktExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S006TGKT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") S006tgkt record, @Param("example") S006tgktExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S006TGKT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") S006tgkt record, @Param("example") S006tgktExample example);
}