package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S018srer;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S018srerExample;
import org.apache.ibatis.annotations.Param;

public interface S018srerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S018SRER
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(S018srerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S018SRER
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(S018srerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S018SRER
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(S018srer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S018SRER
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(S018srer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S018SRER
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<S018srer> selectByExample(S018srerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S018SRER
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") S018srer record, @Param("example") S018srerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S018SRER
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") S018srer record, @Param("example") S018srerExample example);
}