package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S019brer;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S019brerExample;
import org.apache.ibatis.annotations.Param;

public interface S019brerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S019BRER
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(S019brerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S019BRER
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(S019brerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S019BRER
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(S019brer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S019BRER
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(S019brer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S019BRER
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<S019brer> selectByExample(S019brerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S019BRER
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") S019brer record, @Param("example") S019brerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S019BRER
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") S019brer record, @Param("example") S019brerExample example);
}