package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S021brkt;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S021brktExample;
import org.apache.ibatis.annotations.Param;

public interface S021brktMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S021BRKT
     *
     * @mbggenerated Wed Jan 22 09:53:11 JST 2014
     */
    int countByExample(S021brktExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S021BRKT
     *
     * @mbggenerated Wed Jan 22 09:53:11 JST 2014
     */
    int deleteByExample(S021brktExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S021BRKT
     *
     * @mbggenerated Wed Jan 22 09:53:11 JST 2014
     */
    int insert(S021brkt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S021BRKT
     *
     * @mbggenerated Wed Jan 22 09:53:11 JST 2014
     */
    int insertSelective(S021brkt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S021BRKT
     *
     * @mbggenerated Wed Jan 22 09:53:11 JST 2014
     */
    List<S021brkt> selectByExample(S021brktExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S021BRKT
     *
     * @mbggenerated Wed Jan 22 09:53:11 JST 2014
     */
    int updateByExampleSelective(@Param("record") S021brkt record, @Param("example") S021brktExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S021BRKT
     *
     * @mbggenerated Wed Jan 22 09:53:11 JST 2014
     */
    int updateByExample(@Param("record") S021brkt record, @Param("example") S021brktExample example);
}