package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S024ykkt;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S024ykktExample;
import org.apache.ibatis.annotations.Param;

public interface S024ykktMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S024YKKT
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(S024ykktExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S024YKKT
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(S024ykktExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S024YKKT
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(S024ykkt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S024YKKT
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(S024ykkt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S024YKKT
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<S024ykkt> selectByExample(S024ykktExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S024YKKT
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") S024ykkt record, @Param("example") S024ykktExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S024YKKT
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") S024ykkt record, @Param("example") S024ykktExample example);
}