package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S030bhkp;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S030bhkpExample;
import org.apache.ibatis.annotations.Param;

public interface S030bhkpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S030BHKP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(S030bhkpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S030BHKP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(S030bhkpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S030BHKP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(S030bhkp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S030BHKP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(S030bhkp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S030BHKP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<S030bhkp> selectByExample(S030bhkpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S030BHKP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") S030bhkp record, @Param("example") S030bhkpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S030BHKP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") S030bhkp record, @Param("example") S030bhkpExample example);
}