package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S034souf;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S034soufExample;
import org.apache.ibatis.annotations.Param;

public interface S034soufMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S034SOUF
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(S034soufExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S034SOUF
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(S034soufExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S034SOUF
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(S034souf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S034SOUF
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(S034souf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S034SOUF
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<S034souf> selectByExample(S034soufExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S034SOUF
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") S034souf record, @Param("example") S034soufExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S034SOUF
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") S034souf record, @Param("example") S034soufExample example);
}