package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S037seut;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S037seutExample;
import org.apache.ibatis.annotations.Param;

public interface S037seutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S037SEUT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(S037seutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S037SEUT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(S037seutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S037SEUT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(S037seut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S037SEUT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(S037seut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S037SEUT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<S037seut> selectByExample(S037seutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S037SEUT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") S037seut record, @Param("example") S037seutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S037SEUT
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") S037seut record, @Param("example") S037seutExample example);
}