package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S043ukim;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S043ukimExample;
import org.apache.ibatis.annotations.Param;

public interface S043ukimMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S043UKIM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(S043ukimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S043UKIM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(S043ukimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S043UKIM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(S043ukim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S043UKIM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(S043ukim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S043UKIM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<S043ukim> selectByExample(S043ukimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S043UKIM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") S043ukim record, @Param("example") S043ukimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S043UKIM
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") S043ukim record, @Param("example") S043ukimExample example);
}