package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S703itss;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S703itssExample;
import org.apache.ibatis.annotations.Param;

public interface S703itssMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S703ITSS
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(S703itssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S703ITSS
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(S703itssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S703ITSS
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(S703itss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S703ITSS
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(S703itss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S703ITSS
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<S703itss> selectByExample(S703itssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S703ITSS
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") S703itss record, @Param("example") S703itssExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S703ITSS
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") S703itss record, @Param("example") S703itssExample example);
}