package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S708itst;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S708itstExample;
import org.apache.ibatis.annotations.Param;

public interface S708itstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S708ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int countByExample(S708itstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S708ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int deleteByExample(S708itstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S708ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insert(S708itst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S708ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int insertSelective(S708itst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S708ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    List<S708itst> selectByExample(S708itstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S708ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExampleSelective(@Param("record") S708itst record, @Param("example") S708itstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S708ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    int updateByExample(@Param("record") S708itst record, @Param("example") S708itstExample example);
}