package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S903frid;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S903fridExample;
import org.apache.ibatis.annotations.Param;

public interface S903fridMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S903FRID
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(S903fridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S903FRID
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(S903fridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S903FRID
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(S903frid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S903FRID
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(S903frid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S903FRID
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<S903frid> selectByExample(S903fridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S903FRID
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") S903frid record, @Param("example") S903fridExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S903FRID
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") S903frid record, @Param("example") S903fridExample example);
}