package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S904bhhk;
import jp.co.necsoft.web_md.core.common.mybatis.dto.S904bhhkExample;
import org.apache.ibatis.annotations.Param;

public interface S904bhhkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S904BHHK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(S904bhhkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S904BHHK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(S904bhhkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S904BHHK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(S904bhhk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S904BHHK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(S904bhhk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S904BHHK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<S904bhhk> selectByExample(S904bhhkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S904BHHK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") S904bhhk record, @Param("example") S904bhhkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S904BHHK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") S904bhhk record, @Param("example") S904bhhkExample example);
}