package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Sc01btlg;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Sc01btlgExample;
import org.apache.ibatis.annotations.Param;

public interface Sc01btlgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC01BTLG
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(Sc01btlgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC01BTLG
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(Sc01btlgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC01BTLG
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(Sc01btlg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC01BTLG
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(Sc01btlg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC01BTLG
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<Sc01btlg> selectByExample(Sc01btlgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC01BTLG
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") Sc01btlg record, @Param("example") Sc01btlgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC01BTLG
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") Sc01btlg record, @Param("example") Sc01btlgExample example);
}