package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Sc05bkdj;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Sc05bkdjExample;
import org.apache.ibatis.annotations.Param;

public interface Sc05bkdjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC05BKDJ
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(Sc05bkdjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC05BKDJ
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(Sc05bkdjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC05BKDJ
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(Sc05bkdj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC05BKDJ
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(Sc05bkdj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC05BKDJ
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<Sc05bkdj> selectByExample(Sc05bkdjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC05BKDJ
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") Sc05bkdj record, @Param("example") Sc05bkdjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC05BKDJ
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") Sc05bkdj record, @Param("example") Sc05bkdjExample example);
}