package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Sc24wstm;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Sc24wstmExample;
import org.apache.ibatis.annotations.Param;

public interface Sc24wstmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC24WSTM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(Sc24wstmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC24WSTM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(Sc24wstmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC24WSTM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(Sc24wstm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC24WSTM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(Sc24wstm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC24WSTM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<Sc24wstm> selectByExample(Sc24wstmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC24WSTM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") Sc24wstm record, @Param("example") Sc24wstmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC24WSTM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") Sc24wstm record, @Param("example") Sc24wstmExample example);
}