package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Sc90pgnm;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Sc90pgnmExample;
import org.apache.ibatis.annotations.Param;

public interface Sc90pgnmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC90PGNM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(Sc90pgnmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC90PGNM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(Sc90pgnmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC90PGNM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(Sc90pgnm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC90PGNM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(Sc90pgnm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC90PGNM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<Sc90pgnm> selectByExample(Sc90pgnmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC90PGNM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") Sc90pgnm record, @Param("example") Sc90pgnmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.SC90PGNM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") Sc90pgnm record, @Param("example") Sc90pgnmExample example);
}