package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Se25hpnt;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Se25hpntExample;
import org.apache.ibatis.annotations.Param;

public interface Se25hpntMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBMD.SE25HPNT
	 * @mbggenerated  Fri Dec 19 20:53:29 JST 2014
	 */
	int countByExample(Se25hpntExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBMD.SE25HPNT
	 * @mbggenerated  Fri Dec 19 20:53:29 JST 2014
	 */
	int deleteByExample(Se25hpntExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBMD.SE25HPNT
	 * @mbggenerated  Fri Dec 19 20:53:29 JST 2014
	 */
	int insert(Se25hpnt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBMD.SE25HPNT
	 * @mbggenerated  Fri Dec 19 20:53:29 JST 2014
	 */
	int insertSelective(Se25hpnt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBMD.SE25HPNT
	 * @mbggenerated  Fri Dec 19 20:53:29 JST 2014
	 */
	List<Se25hpnt> selectByExample(Se25hpntExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBMD.SE25HPNT
	 * @mbggenerated  Fri Dec 19 20:53:29 JST 2014
	 */
	int updateByExampleSelective(@Param("record") Se25hpnt record,
			@Param("example") Se25hpntExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEBMD.SE25HPNT
	 * @mbggenerated  Fri Dec 19 20:53:29 JST 2014
	 */
	int updateByExample(@Param("record") Se25hpnt record,
			@Param("example") Se25hpntExample example);
}