package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.T005Facingitem;
import jp.co.necsoft.web_md.core.common.mybatis.dto.T005FacingitemExample;
import org.apache.ibatis.annotations.Param;

public interface T005FacingitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.T005_FACINGITEM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(T005FacingitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.T005_FACINGITEM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(T005FacingitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.T005_FACINGITEM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(T005Facingitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.T005_FACINGITEM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(T005Facingitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.T005_FACINGITEM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<T005Facingitem> selectByExample(T005FacingitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.T005_FACINGITEM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") T005Facingitem record, @Param("example") T005FacingitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.T005_FACINGITEM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") T005Facingitem record, @Param("example") T005FacingitemExample example);
}