package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U001Specialsell;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U001SpecialsellExample;
import org.apache.ibatis.annotations.Param;

public interface U001SpecialsellMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U001_SPECIALSELL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int countByExample(U001SpecialsellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U001_SPECIALSELL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int deleteByExample(U001SpecialsellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U001_SPECIALSELL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insert(U001Specialsell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U001_SPECIALSELL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int insertSelective(U001Specialsell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U001_SPECIALSELL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    List<U001Specialsell> selectByExample(U001SpecialsellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U001_SPECIALSELL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExampleSelective(@Param("record") U001Specialsell record, @Param("example") U001SpecialsellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U001_SPECIALSELL
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    int updateByExample(@Param("record") U001Specialsell record, @Param("example") U001SpecialsellExample example);
}