package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U016bmnj;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U016bmnjExample;
import org.apache.ibatis.annotations.Param;

public interface U016bmnjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U016BMNJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int countByExample(U016bmnjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U016BMNJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int deleteByExample(U016bmnjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U016BMNJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insert(U016bmnj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U016BMNJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insertSelective(U016bmnj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U016BMNJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    List<U016bmnj> selectByExample(U016bmnjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U016BMNJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExampleSelective(@Param("record") U016bmnj record, @Param("example") U016bmnjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U016BMNJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExample(@Param("record") U016bmnj record, @Param("example") U016bmnjExample example);
}