package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U021tenj;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U021tenjExample;
import org.apache.ibatis.annotations.Param;

public interface U021tenjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U021TENJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int countByExample(U021tenjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U021TENJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int deleteByExample(U021tenjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U021TENJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insert(U021tenj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U021TENJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insertSelective(U021tenj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U021TENJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    List<U021tenj> selectByExample(U021tenjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U021TENJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExampleSelective(@Param("record") U021tenj record, @Param("example") U021tenjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U021TENJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExample(@Param("record") U021tenj record, @Param("example") U021tenjExample example);
}