package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U022bmnj;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U022bmnjExample;
import org.apache.ibatis.annotations.Param;

public interface U022bmnjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U022BMNJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int countByExample(U022bmnjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U022BMNJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int deleteByExample(U022bmnjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U022BMNJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insert(U022bmnj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U022BMNJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insertSelective(U022bmnj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U022BMNJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    List<U022bmnj> selectByExample(U022bmnjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U022BMNJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExampleSelective(@Param("record") U022bmnj record, @Param("example") U022bmnjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U022BMNJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExample(@Param("record") U022bmnj record, @Param("example") U022bmnjExample example);
}