package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U034tanj;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U034tanjExample;
import org.apache.ibatis.annotations.Param;

public interface U034tanjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U034TANJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int countByExample(U034tanjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U034TANJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int deleteByExample(U034tanjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U034TANJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insert(U034tanj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U034TANJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insertSelective(U034tanj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U034TANJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    List<U034tanj> selectByExample(U034tanjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U034TANJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExampleSelective(@Param("record") U034tanj record, @Param("example") U034tanjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U034TANJ
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExample(@Param("record") U034tanj record, @Param("example") U034tanjExample example);
}