package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U035arij;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U035arijExample;
import org.apache.ibatis.annotations.Param;

public interface U035arijMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.U035ARIJ
     *
     * @mbggenerated Thu Mar 26 08:23:57 ICT 2015
     */
    int countByExample(U035arijExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.U035ARIJ
     *
     * @mbggenerated Thu Mar 26 08:23:57 ICT 2015
     */
    int deleteByExample(U035arijExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.U035ARIJ
     *
     * @mbggenerated Thu Mar 26 08:23:57 ICT 2015
     */
    int insert(U035arij record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.U035ARIJ
     *
     * @mbggenerated Thu Mar 26 08:23:57 ICT 2015
     */
    int insertSelective(U035arij record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.U035ARIJ
     *
     * @mbggenerated Thu Mar 26 08:23:57 ICT 2015
     */
    List<U035arij> selectByExample(U035arijExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.U035ARIJ
     *
     * @mbggenerated Thu Mar 26 08:23:57 ICT 2015
     */
    int updateByExampleSelective(@Param("record") U035arij record, @Param("example") U035arijExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.U035ARIJ
     *
     * @mbggenerated Thu Mar 26 08:23:57 ICT 2015
     */
    int updateByExample(@Param("record") U035arij record, @Param("example") U035arijExample example);
}