package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U041tent;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U041tentExample;
import org.apache.ibatis.annotations.Param;

public interface U041tentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U041TENT
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int countByExample(U041tentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U041TENT
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int deleteByExample(U041tentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U041TENT
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insert(U041tent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U041TENT
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insertSelective(U041tent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U041TENT
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    List<U041tent> selectByExample(U041tentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U041TENT
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExampleSelective(@Param("record") U041tent record, @Param("example") U041tentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U041TENT
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExample(@Param("record") U041tent record, @Param("example") U041tentExample example);
}