package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U053yerr;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U053yerrExample;
import org.apache.ibatis.annotations.Param;

public interface U053yerrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U053YERR
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int countByExample(U053yerrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U053YERR
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int deleteByExample(U053yerrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U053YERR
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insert(U053yerr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U053YERR
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insertSelective(U053yerr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U053YERR
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    List<U053yerr> selectByExample(U053yerrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U053YERR
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExampleSelective(@Param("record") U053yerr record, @Param("example") U053yerrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U053YERR
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExample(@Param("record") U053yerr record, @Param("example") U053yerrExample example);
}