package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U703kydt;
import jp.co.necsoft.web_md.core.common.mybatis.dto.U703kydtExample;
import org.apache.ibatis.annotations.Param;

public interface U703kydtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U703KYDT
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int countByExample(U703kydtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U703KYDT
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int deleteByExample(U703kydtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U703KYDT
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insert(U703kydt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U703KYDT
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insertSelective(U703kydt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U703KYDT
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    List<U703kydt> selectByExample(U703kydtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U703KYDT
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExampleSelective(@Param("record") U703kydt record, @Param("example") U703kydtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.U703KYDT
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExample(@Param("record") U703kydt record, @Param("example") U703kydtExample example);
}