package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.X701saih;
import jp.co.necsoft.web_md.core.common.mybatis.dto.X701saihExample;
import org.apache.ibatis.annotations.Param;

public interface X701saihMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.X701SAIH
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int countByExample(X701saihExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.X701SAIH
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int deleteByExample(X701saihExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.X701SAIH
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insert(X701saih record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.X701SAIH
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insertSelective(X701saih record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.X701SAIH
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    List<X701saih> selectByExample(X701saihExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.X701SAIH
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExampleSelective(@Param("record") X701saih record, @Param("example") X701saihExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.X701SAIH
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExample(@Param("record") X701saih record, @Param("example") X701saihExample example);
}