package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.X702saim;
import jp.co.necsoft.web_md.core.common.mybatis.dto.X702saimExample;
import org.apache.ibatis.annotations.Param;

public interface X702saimMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.X702SAIM
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int countByExample(X702saimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.X702SAIM
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int deleteByExample(X702saimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.X702SAIM
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insert(X702saim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.X702SAIM
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insertSelective(X702saim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.X702SAIM
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    List<X702saim> selectByExample(X702saimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.X702SAIM
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExampleSelective(@Param("record") X702saim record, @Param("example") X702saimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.X702SAIM
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExample(@Param("record") X702saim record, @Param("example") X702saimExample example);
}