package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Y004tshf;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Y004tshfExample;
import org.apache.ibatis.annotations.Param;

public interface Y004tshfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.Y004TSHF
     *
     * @mbggenerated Thu Jan 22 09:41:11 ICT 2015
     */
    int countByExample(Y004tshfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.Y004TSHF
     *
     * @mbggenerated Thu Jan 22 09:41:11 ICT 2015
     */
    int deleteByExample(Y004tshfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.Y004TSHF
     *
     * @mbggenerated Thu Jan 22 09:41:11 ICT 2015
     */
    int insert(Y004tshf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.Y004TSHF
     *
     * @mbggenerated Thu Jan 22 09:41:11 ICT 2015
     */
    int insertSelective(Y004tshf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.Y004TSHF
     *
     * @mbggenerated Thu Jan 22 09:41:11 ICT 2015
     */
    List<Y004tshf> selectByExample(Y004tshfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.Y004TSHF
     *
     * @mbggenerated Thu Jan 22 09:41:11 ICT 2015
     */
    int updateByExampleSelective(@Param("record") Y004tshf record, @Param("example") Y004tshfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.Y004TSHF
     *
     * @mbggenerated Thu Jan 22 09:41:11 ICT 2015
     */
    int updateByExample(@Param("record") Y004tshf record, @Param("example") Y004tshfExample example);
}