package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Y012tntb;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Y012tntbExample;
import org.apache.ibatis.annotations.Param;

public interface Y012tntbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.Y012TNTB
     *
     * @mbggenerated Thu Jan 22 09:41:33 ICT 2015
     */
    int countByExample(Y012tntbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.Y012TNTB
     *
     * @mbggenerated Thu Jan 22 09:41:33 ICT 2015
     */
    int deleteByExample(Y012tntbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.Y012TNTB
     *
     * @mbggenerated Thu Jan 22 09:41:33 ICT 2015
     */
    int insert(Y012tntb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.Y012TNTB
     *
     * @mbggenerated Thu Jan 22 09:41:33 ICT 2015
     */
    int insertSelective(Y012tntb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.Y012TNTB
     *
     * @mbggenerated Thu Jan 22 09:41:33 ICT 2015
     */
    List<Y012tntb> selectByExample(Y012tntbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.Y012TNTB
     *
     * @mbggenerated Thu Jan 22 09:41:33 ICT 2015
     */
    int updateByExampleSelective(@Param("record") Y012tntb record, @Param("example") Y012tntbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMDTEST.Y012TNTB
     *
     * @mbggenerated Thu Jan 22 09:41:33 ICT 2015
     */
    int updateByExample(@Param("record") Y012tntb record, @Param("example") Y012tntbExample example);
}