package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Z004tbmn;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Z004tbmnExample;
import org.apache.ibatis.annotations.Param;

public interface Z004tbmnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z004TBMN
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int countByExample(Z004tbmnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z004TBMN
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int deleteByExample(Z004tbmnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z004TBMN
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insert(Z004tbmn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z004TBMN
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insertSelective(Z004tbmn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z004TBMN
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    List<Z004tbmn> selectByExample(Z004tbmnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z004TBMN
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExampleSelective(@Param("record") Z004tbmn record, @Param("example") Z004tbmnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z004TBMN
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExample(@Param("record") Z004tbmn record, @Param("example") Z004tbmnExample example);
}