package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Z024bmnc;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Z024bmncExample;
import org.apache.ibatis.annotations.Param;

public interface Z024bmncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z024BMNC
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int countByExample(Z024bmncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z024BMNC
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int deleteByExample(Z024bmncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z024BMNC
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insert(Z024bmnc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z024BMNC
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insertSelective(Z024bmnc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z024BMNC
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    List<Z024bmnc> selectByExample(Z024bmncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z024BMNC
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExampleSelective(@Param("record") Z024bmnc record, @Param("example") Z024bmncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z024BMNC
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExample(@Param("record") Z024bmnc record, @Param("example") Z024bmncExample example);
}