package jp.co.necsoft.web_md.core.common.mybatis.dao;

import java.util.List;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Z700zsok;
import jp.co.necsoft.web_md.core.common.mybatis.dto.Z700zsokExample;
import org.apache.ibatis.annotations.Param;

public interface Z700zsokMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z700ZSOK
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int countByExample(Z700zsokExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z700ZSOK
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int deleteByExample(Z700zsokExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z700ZSOK
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insert(Z700zsok record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z700ZSOK
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int insertSelective(Z700zsok record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z700ZSOK
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    List<Z700zsok> selectByExample(Z700zsokExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z700ZSOK
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExampleSelective(@Param("record") Z700zsok record, @Param("example") Z700zsokExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.Z700ZSOK
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    int updateByExample(@Param("record") Z700zsok record, @Param("example") Z700zsokExample example);
}