package jp.co.necsoft.web_md.core.common.mybatis.dto;

import java.util.ArrayList;
import java.util.List;

public class H050hatpExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public H050hatpExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andKaiCdIsNull() {
            addCriterion("KAI_CD is null");
            return (Criteria) this;
        }

        public Criteria andKaiCdIsNotNull() {
            addCriterion("KAI_CD is not null");
            return (Criteria) this;
        }

        public Criteria andKaiCdEqualTo(String value) {
            addCriterion("KAI_CD =", value, "kaiCd");
            return (Criteria) this;
        }

        public Criteria andKaiCdNotEqualTo(String value) {
            addCriterion("KAI_CD <>", value, "kaiCd");
            return (Criteria) this;
        }

        public Criteria andKaiCdGreaterThan(String value) {
            addCriterion("KAI_CD >", value, "kaiCd");
            return (Criteria) this;
        }

        public Criteria andKaiCdGreaterThanOrEqualTo(String value) {
            addCriterion("KAI_CD >=", value, "kaiCd");
            return (Criteria) this;
        }

        public Criteria andKaiCdLessThan(String value) {
            addCriterion("KAI_CD <", value, "kaiCd");
            return (Criteria) this;
        }

        public Criteria andKaiCdLessThanOrEqualTo(String value) {
            addCriterion("KAI_CD <=", value, "kaiCd");
            return (Criteria) this;
        }

        public Criteria andKaiCdLike(String value) {
            addCriterion("KAI_CD like", value, "kaiCd");
            return (Criteria) this;
        }

        public Criteria andKaiCdNotLike(String value) {
            addCriterion("KAI_CD not like", value, "kaiCd");
            return (Criteria) this;
        }

        public Criteria andKaiCdIn(List<String> values) {
            addCriterion("KAI_CD in", values, "kaiCd");
            return (Criteria) this;
        }

        public Criteria andKaiCdNotIn(List<String> values) {
            addCriterion("KAI_CD not in", values, "kaiCd");
            return (Criteria) this;
        }

        public Criteria andKaiCdBetween(String value1, String value2) {
            addCriterion("KAI_CD between", value1, value2, "kaiCd");
            return (Criteria) this;
        }

        public Criteria andKaiCdNotBetween(String value1, String value2) {
            addCriterion("KAI_CD not between", value1, value2, "kaiCd");
            return (Criteria) this;
        }

        public Criteria andJgbCdIsNull() {
            addCriterion("JGB_CD is null");
            return (Criteria) this;
        }

        public Criteria andJgbCdIsNotNull() {
            addCriterion("JGB_CD is not null");
            return (Criteria) this;
        }

        public Criteria andJgbCdEqualTo(String value) {
            addCriterion("JGB_CD =", value, "jgbCd");
            return (Criteria) this;
        }

        public Criteria andJgbCdNotEqualTo(String value) {
            addCriterion("JGB_CD <>", value, "jgbCd");
            return (Criteria) this;
        }

        public Criteria andJgbCdGreaterThan(String value) {
            addCriterion("JGB_CD >", value, "jgbCd");
            return (Criteria) this;
        }

        public Criteria andJgbCdGreaterThanOrEqualTo(String value) {
            addCriterion("JGB_CD >=", value, "jgbCd");
            return (Criteria) this;
        }

        public Criteria andJgbCdLessThan(String value) {
            addCriterion("JGB_CD <", value, "jgbCd");
            return (Criteria) this;
        }

        public Criteria andJgbCdLessThanOrEqualTo(String value) {
            addCriterion("JGB_CD <=", value, "jgbCd");
            return (Criteria) this;
        }

        public Criteria andJgbCdLike(String value) {
            addCriterion("JGB_CD like", value, "jgbCd");
            return (Criteria) this;
        }

        public Criteria andJgbCdNotLike(String value) {
            addCriterion("JGB_CD not like", value, "jgbCd");
            return (Criteria) this;
        }

        public Criteria andJgbCdIn(List<String> values) {
            addCriterion("JGB_CD in", values, "jgbCd");
            return (Criteria) this;
        }

        public Criteria andJgbCdNotIn(List<String> values) {
            addCriterion("JGB_CD not in", values, "jgbCd");
            return (Criteria) this;
        }

        public Criteria andJgbCdBetween(String value1, String value2) {
            addCriterion("JGB_CD between", value1, value2, "jgbCd");
            return (Criteria) this;
        }

        public Criteria andJgbCdNotBetween(String value1, String value2) {
            addCriterion("JGB_CD not between", value1, value2, "jgbCd");
            return (Criteria) this;
        }

        public Criteria andTenCdIsNull() {
            addCriterion("TEN_CD is null");
            return (Criteria) this;
        }

        public Criteria andTenCdIsNotNull() {
            addCriterion("TEN_CD is not null");
            return (Criteria) this;
        }

        public Criteria andTenCdEqualTo(String value) {
            addCriterion("TEN_CD =", value, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdNotEqualTo(String value) {
            addCriterion("TEN_CD <>", value, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdGreaterThan(String value) {
            addCriterion("TEN_CD >", value, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdGreaterThanOrEqualTo(String value) {
            addCriterion("TEN_CD >=", value, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdLessThan(String value) {
            addCriterion("TEN_CD <", value, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdLessThanOrEqualTo(String value) {
            addCriterion("TEN_CD <=", value, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdLike(String value) {
            addCriterion("TEN_CD like", value, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdNotLike(String value) {
            addCriterion("TEN_CD not like", value, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdIn(List<String> values) {
            addCriterion("TEN_CD in", values, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdNotIn(List<String> values) {
            addCriterion("TEN_CD not in", values, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdBetween(String value1, String value2) {
            addCriterion("TEN_CD between", value1, value2, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdNotBetween(String value1, String value2) {
            addCriterion("TEN_CD not between", value1, value2, "tenCd");
            return (Criteria) this;
        }

        public Criteria andDbmnCdIsNull() {
            addCriterion("DBMN_CD is null");
            return (Criteria) this;
        }

        public Criteria andDbmnCdIsNotNull() {
            addCriterion("DBMN_CD is not null");
            return (Criteria) this;
        }

        public Criteria andDbmnCdEqualTo(String value) {
            addCriterion("DBMN_CD =", value, "dbmnCd");
            return (Criteria) this;
        }

        public Criteria andDbmnCdNotEqualTo(String value) {
            addCriterion("DBMN_CD <>", value, "dbmnCd");
            return (Criteria) this;
        }

        public Criteria andDbmnCdGreaterThan(String value) {
            addCriterion("DBMN_CD >", value, "dbmnCd");
            return (Criteria) this;
        }

        public Criteria andDbmnCdGreaterThanOrEqualTo(String value) {
            addCriterion("DBMN_CD >=", value, "dbmnCd");
            return (Criteria) this;
        }

        public Criteria andDbmnCdLessThan(String value) {
            addCriterion("DBMN_CD <", value, "dbmnCd");
            return (Criteria) this;
        }

        public Criteria andDbmnCdLessThanOrEqualTo(String value) {
            addCriterion("DBMN_CD <=", value, "dbmnCd");
            return (Criteria) this;
        }

        public Criteria andDbmnCdLike(String value) {
            addCriterion("DBMN_CD like", value, "dbmnCd");
            return (Criteria) this;
        }

        public Criteria andDbmnCdNotLike(String value) {
            addCriterion("DBMN_CD not like", value, "dbmnCd");
            return (Criteria) this;
        }

        public Criteria andDbmnCdIn(List<String> values) {
            addCriterion("DBMN_CD in", values, "dbmnCd");
            return (Criteria) this;
        }

        public Criteria andDbmnCdNotIn(List<String> values) {
            addCriterion("DBMN_CD not in", values, "dbmnCd");
            return (Criteria) this;
        }

        public Criteria andDbmnCdBetween(String value1, String value2) {
            addCriterion("DBMN_CD between", value1, value2, "dbmnCd");
            return (Criteria) this;
        }

        public Criteria andDbmnCdNotBetween(String value1, String value2) {
            addCriterion("DBMN_CD not between", value1, value2, "dbmnCd");
            return (Criteria) this;
        }

        public Criteria andBmnCdIsNull() {
            addCriterion("BMN_CD is null");
            return (Criteria) this;
        }

        public Criteria andBmnCdIsNotNull() {
            addCriterion("BMN_CD is not null");
            return (Criteria) this;
        }

        public Criteria andBmnCdEqualTo(String value) {
            addCriterion("BMN_CD =", value, "bmnCd");
            return (Criteria) this;
        }

        public Criteria andBmnCdNotEqualTo(String value) {
            addCriterion("BMN_CD <>", value, "bmnCd");
            return (Criteria) this;
        }

        public Criteria andBmnCdGreaterThan(String value) {
            addCriterion("BMN_CD >", value, "bmnCd");
            return (Criteria) this;
        }

        public Criteria andBmnCdGreaterThanOrEqualTo(String value) {
            addCriterion("BMN_CD >=", value, "bmnCd");
            return (Criteria) this;
        }

        public Criteria andBmnCdLessThan(String value) {
            addCriterion("BMN_CD <", value, "bmnCd");
            return (Criteria) this;
        }

        public Criteria andBmnCdLessThanOrEqualTo(String value) {
            addCriterion("BMN_CD <=", value, "bmnCd");
            return (Criteria) this;
        }

        public Criteria andBmnCdLike(String value) {
            addCriterion("BMN_CD like", value, "bmnCd");
            return (Criteria) this;
        }

        public Criteria andBmnCdNotLike(String value) {
            addCriterion("BMN_CD not like", value, "bmnCd");
            return (Criteria) this;
        }

        public Criteria andBmnCdIn(List<String> values) {
            addCriterion("BMN_CD in", values, "bmnCd");
            return (Criteria) this;
        }

        public Criteria andBmnCdNotIn(List<String> values) {
            addCriterion("BMN_CD not in", values, "bmnCd");
            return (Criteria) this;
        }

        public Criteria andBmnCdBetween(String value1, String value2) {
            addCriterion("BMN_CD between", value1, value2, "bmnCd");
            return (Criteria) this;
        }

        public Criteria andBmnCdNotBetween(String value1, String value2) {
            addCriterion("BMN_CD not between", value1, value2, "bmnCd");
            return (Criteria) this;
        }

        public Criteria andCbnrCdIsNull() {
            addCriterion("CBNR_CD is null");
            return (Criteria) this;
        }

        public Criteria andCbnrCdIsNotNull() {
            addCriterion("CBNR_CD is not null");
            return (Criteria) this;
        }

        public Criteria andCbnrCdEqualTo(String value) {
            addCriterion("CBNR_CD =", value, "cbnrCd");
            return (Criteria) this;
        }

        public Criteria andCbnrCdNotEqualTo(String value) {
            addCriterion("CBNR_CD <>", value, "cbnrCd");
            return (Criteria) this;
        }

        public Criteria andCbnrCdGreaterThan(String value) {
            addCriterion("CBNR_CD >", value, "cbnrCd");
            return (Criteria) this;
        }

        public Criteria andCbnrCdGreaterThanOrEqualTo(String value) {
            addCriterion("CBNR_CD >=", value, "cbnrCd");
            return (Criteria) this;
        }

        public Criteria andCbnrCdLessThan(String value) {
            addCriterion("CBNR_CD <", value, "cbnrCd");
            return (Criteria) this;
        }

        public Criteria andCbnrCdLessThanOrEqualTo(String value) {
            addCriterion("CBNR_CD <=", value, "cbnrCd");
            return (Criteria) this;
        }

        public Criteria andCbnrCdLike(String value) {
            addCriterion("CBNR_CD like", value, "cbnrCd");
            return (Criteria) this;
        }

        public Criteria andCbnrCdNotLike(String value) {
            addCriterion("CBNR_CD not like", value, "cbnrCd");
            return (Criteria) this;
        }

        public Criteria andCbnrCdIn(List<String> values) {
            addCriterion("CBNR_CD in", values, "cbnrCd");
            return (Criteria) this;
        }

        public Criteria andCbnrCdNotIn(List<String> values) {
            addCriterion("CBNR_CD not in", values, "cbnrCd");
            return (Criteria) this;
        }

        public Criteria andCbnrCdBetween(String value1, String value2) {
            addCriterion("CBNR_CD between", value1, value2, "cbnrCd");
            return (Criteria) this;
        }

        public Criteria andCbnrCdNotBetween(String value1, String value2) {
            addCriterion("CBNR_CD not between", value1, value2, "cbnrCd");
            return (Criteria) this;
        }

        public Criteria andLtMonIsNull() {
            addCriterion("LT_MON is null");
            return (Criteria) this;
        }

        public Criteria andLtMonIsNotNull() {
            addCriterion("LT_MON is not null");
            return (Criteria) this;
        }

        public Criteria andLtMonEqualTo(Short value) {
            addCriterion("LT_MON =", value, "ltMon");
            return (Criteria) this;
        }

        public Criteria andLtMonNotEqualTo(Short value) {
            addCriterion("LT_MON <>", value, "ltMon");
            return (Criteria) this;
        }

        public Criteria andLtMonGreaterThan(Short value) {
            addCriterion("LT_MON >", value, "ltMon");
            return (Criteria) this;
        }

        public Criteria andLtMonGreaterThanOrEqualTo(Short value) {
            addCriterion("LT_MON >=", value, "ltMon");
            return (Criteria) this;
        }

        public Criteria andLtMonLessThan(Short value) {
            addCriterion("LT_MON <", value, "ltMon");
            return (Criteria) this;
        }

        public Criteria andLtMonLessThanOrEqualTo(Short value) {
            addCriterion("LT_MON <=", value, "ltMon");
            return (Criteria) this;
        }

        public Criteria andLtMonIn(List<Short> values) {
            addCriterion("LT_MON in", values, "ltMon");
            return (Criteria) this;
        }

        public Criteria andLtMonNotIn(List<Short> values) {
            addCriterion("LT_MON not in", values, "ltMon");
            return (Criteria) this;
        }

        public Criteria andLtMonBetween(Short value1, Short value2) {
            addCriterion("LT_MON between", value1, value2, "ltMon");
            return (Criteria) this;
        }

        public Criteria andLtMonNotBetween(Short value1, Short value2) {
            addCriterion("LT_MON not between", value1, value2, "ltMon");
            return (Criteria) this;
        }

        public Criteria andLtTueIsNull() {
            addCriterion("LT_TUE is null");
            return (Criteria) this;
        }

        public Criteria andLtTueIsNotNull() {
            addCriterion("LT_TUE is not null");
            return (Criteria) this;
        }

        public Criteria andLtTueEqualTo(Short value) {
            addCriterion("LT_TUE =", value, "ltTue");
            return (Criteria) this;
        }

        public Criteria andLtTueNotEqualTo(Short value) {
            addCriterion("LT_TUE <>", value, "ltTue");
            return (Criteria) this;
        }

        public Criteria andLtTueGreaterThan(Short value) {
            addCriterion("LT_TUE >", value, "ltTue");
            return (Criteria) this;
        }

        public Criteria andLtTueGreaterThanOrEqualTo(Short value) {
            addCriterion("LT_TUE >=", value, "ltTue");
            return (Criteria) this;
        }

        public Criteria andLtTueLessThan(Short value) {
            addCriterion("LT_TUE <", value, "ltTue");
            return (Criteria) this;
        }

        public Criteria andLtTueLessThanOrEqualTo(Short value) {
            addCriterion("LT_TUE <=", value, "ltTue");
            return (Criteria) this;
        }

        public Criteria andLtTueIn(List<Short> values) {
            addCriterion("LT_TUE in", values, "ltTue");
            return (Criteria) this;
        }

        public Criteria andLtTueNotIn(List<Short> values) {
            addCriterion("LT_TUE not in", values, "ltTue");
            return (Criteria) this;
        }

        public Criteria andLtTueBetween(Short value1, Short value2) {
            addCriterion("LT_TUE between", value1, value2, "ltTue");
            return (Criteria) this;
        }

        public Criteria andLtTueNotBetween(Short value1, Short value2) {
            addCriterion("LT_TUE not between", value1, value2, "ltTue");
            return (Criteria) this;
        }

        public Criteria andLtWedIsNull() {
            addCriterion("LT_WED is null");
            return (Criteria) this;
        }

        public Criteria andLtWedIsNotNull() {
            addCriterion("LT_WED is not null");
            return (Criteria) this;
        }

        public Criteria andLtWedEqualTo(Short value) {
            addCriterion("LT_WED =", value, "ltWed");
            return (Criteria) this;
        }

        public Criteria andLtWedNotEqualTo(Short value) {
            addCriterion("LT_WED <>", value, "ltWed");
            return (Criteria) this;
        }

        public Criteria andLtWedGreaterThan(Short value) {
            addCriterion("LT_WED >", value, "ltWed");
            return (Criteria) this;
        }

        public Criteria andLtWedGreaterThanOrEqualTo(Short value) {
            addCriterion("LT_WED >=", value, "ltWed");
            return (Criteria) this;
        }

        public Criteria andLtWedLessThan(Short value) {
            addCriterion("LT_WED <", value, "ltWed");
            return (Criteria) this;
        }

        public Criteria andLtWedLessThanOrEqualTo(Short value) {
            addCriterion("LT_WED <=", value, "ltWed");
            return (Criteria) this;
        }

        public Criteria andLtWedIn(List<Short> values) {
            addCriterion("LT_WED in", values, "ltWed");
            return (Criteria) this;
        }

        public Criteria andLtWedNotIn(List<Short> values) {
            addCriterion("LT_WED not in", values, "ltWed");
            return (Criteria) this;
        }

        public Criteria andLtWedBetween(Short value1, Short value2) {
            addCriterion("LT_WED between", value1, value2, "ltWed");
            return (Criteria) this;
        }

        public Criteria andLtWedNotBetween(Short value1, Short value2) {
            addCriterion("LT_WED not between", value1, value2, "ltWed");
            return (Criteria) this;
        }

        public Criteria andLtThuIsNull() {
            addCriterion("LT_THU is null");
            return (Criteria) this;
        }

        public Criteria andLtThuIsNotNull() {
            addCriterion("LT_THU is not null");
            return (Criteria) this;
        }

        public Criteria andLtThuEqualTo(Short value) {
            addCriterion("LT_THU =", value, "ltThu");
            return (Criteria) this;
        }

        public Criteria andLtThuNotEqualTo(Short value) {
            addCriterion("LT_THU <>", value, "ltThu");
            return (Criteria) this;
        }

        public Criteria andLtThuGreaterThan(Short value) {
            addCriterion("LT_THU >", value, "ltThu");
            return (Criteria) this;
        }

        public Criteria andLtThuGreaterThanOrEqualTo(Short value) {
            addCriterion("LT_THU >=", value, "ltThu");
            return (Criteria) this;
        }

        public Criteria andLtThuLessThan(Short value) {
            addCriterion("LT_THU <", value, "ltThu");
            return (Criteria) this;
        }

        public Criteria andLtThuLessThanOrEqualTo(Short value) {
            addCriterion("LT_THU <=", value, "ltThu");
            return (Criteria) this;
        }

        public Criteria andLtThuIn(List<Short> values) {
            addCriterion("LT_THU in", values, "ltThu");
            return (Criteria) this;
        }

        public Criteria andLtThuNotIn(List<Short> values) {
            addCriterion("LT_THU not in", values, "ltThu");
            return (Criteria) this;
        }

        public Criteria andLtThuBetween(Short value1, Short value2) {
            addCriterion("LT_THU between", value1, value2, "ltThu");
            return (Criteria) this;
        }

        public Criteria andLtThuNotBetween(Short value1, Short value2) {
            addCriterion("LT_THU not between", value1, value2, "ltThu");
            return (Criteria) this;
        }

        public Criteria andLtFriIsNull() {
            addCriterion("LT_FRI is null");
            return (Criteria) this;
        }

        public Criteria andLtFriIsNotNull() {
            addCriterion("LT_FRI is not null");
            return (Criteria) this;
        }

        public Criteria andLtFriEqualTo(Short value) {
            addCriterion("LT_FRI =", value, "ltFri");
            return (Criteria) this;
        }

        public Criteria andLtFriNotEqualTo(Short value) {
            addCriterion("LT_FRI <>", value, "ltFri");
            return (Criteria) this;
        }

        public Criteria andLtFriGreaterThan(Short value) {
            addCriterion("LT_FRI >", value, "ltFri");
            return (Criteria) this;
        }

        public Criteria andLtFriGreaterThanOrEqualTo(Short value) {
            addCriterion("LT_FRI >=", value, "ltFri");
            return (Criteria) this;
        }

        public Criteria andLtFriLessThan(Short value) {
            addCriterion("LT_FRI <", value, "ltFri");
            return (Criteria) this;
        }

        public Criteria andLtFriLessThanOrEqualTo(Short value) {
            addCriterion("LT_FRI <=", value, "ltFri");
            return (Criteria) this;
        }

        public Criteria andLtFriIn(List<Short> values) {
            addCriterion("LT_FRI in", values, "ltFri");
            return (Criteria) this;
        }

        public Criteria andLtFriNotIn(List<Short> values) {
            addCriterion("LT_FRI not in", values, "ltFri");
            return (Criteria) this;
        }

        public Criteria andLtFriBetween(Short value1, Short value2) {
            addCriterion("LT_FRI between", value1, value2, "ltFri");
            return (Criteria) this;
        }

        public Criteria andLtFriNotBetween(Short value1, Short value2) {
            addCriterion("LT_FRI not between", value1, value2, "ltFri");
            return (Criteria) this;
        }

        public Criteria andLtSatIsNull() {
            addCriterion("LT_SAT is null");
            return (Criteria) this;
        }

        public Criteria andLtSatIsNotNull() {
            addCriterion("LT_SAT is not null");
            return (Criteria) this;
        }

        public Criteria andLtSatEqualTo(Short value) {
            addCriterion("LT_SAT =", value, "ltSat");
            return (Criteria) this;
        }

        public Criteria andLtSatNotEqualTo(Short value) {
            addCriterion("LT_SAT <>", value, "ltSat");
            return (Criteria) this;
        }

        public Criteria andLtSatGreaterThan(Short value) {
            addCriterion("LT_SAT >", value, "ltSat");
            return (Criteria) this;
        }

        public Criteria andLtSatGreaterThanOrEqualTo(Short value) {
            addCriterion("LT_SAT >=", value, "ltSat");
            return (Criteria) this;
        }

        public Criteria andLtSatLessThan(Short value) {
            addCriterion("LT_SAT <", value, "ltSat");
            return (Criteria) this;
        }

        public Criteria andLtSatLessThanOrEqualTo(Short value) {
            addCriterion("LT_SAT <=", value, "ltSat");
            return (Criteria) this;
        }

        public Criteria andLtSatIn(List<Short> values) {
            addCriterion("LT_SAT in", values, "ltSat");
            return (Criteria) this;
        }

        public Criteria andLtSatNotIn(List<Short> values) {
            addCriterion("LT_SAT not in", values, "ltSat");
            return (Criteria) this;
        }

        public Criteria andLtSatBetween(Short value1, Short value2) {
            addCriterion("LT_SAT between", value1, value2, "ltSat");
            return (Criteria) this;
        }

        public Criteria andLtSatNotBetween(Short value1, Short value2) {
            addCriterion("LT_SAT not between", value1, value2, "ltSat");
            return (Criteria) this;
        }

        public Criteria andLtSunIsNull() {
            addCriterion("LT_SUN is null");
            return (Criteria) this;
        }

        public Criteria andLtSunIsNotNull() {
            addCriterion("LT_SUN is not null");
            return (Criteria) this;
        }

        public Criteria andLtSunEqualTo(Short value) {
            addCriterion("LT_SUN =", value, "ltSun");
            return (Criteria) this;
        }

        public Criteria andLtSunNotEqualTo(Short value) {
            addCriterion("LT_SUN <>", value, "ltSun");
            return (Criteria) this;
        }

        public Criteria andLtSunGreaterThan(Short value) {
            addCriterion("LT_SUN >", value, "ltSun");
            return (Criteria) this;
        }

        public Criteria andLtSunGreaterThanOrEqualTo(Short value) {
            addCriterion("LT_SUN >=", value, "ltSun");
            return (Criteria) this;
        }

        public Criteria andLtSunLessThan(Short value) {
            addCriterion("LT_SUN <", value, "ltSun");
            return (Criteria) this;
        }

        public Criteria andLtSunLessThanOrEqualTo(Short value) {
            addCriterion("LT_SUN <=", value, "ltSun");
            return (Criteria) this;
        }

        public Criteria andLtSunIn(List<Short> values) {
            addCriterion("LT_SUN in", values, "ltSun");
            return (Criteria) this;
        }

        public Criteria andLtSunNotIn(List<Short> values) {
            addCriterion("LT_SUN not in", values, "ltSun");
            return (Criteria) this;
        }

        public Criteria andLtSunBetween(Short value1, Short value2) {
            addCriterion("LT_SUN between", value1, value2, "ltSun");
            return (Criteria) this;
        }

        public Criteria andLtSunNotBetween(Short value1, Short value2) {
            addCriterion("LT_SUN not between", value1, value2, "ltSun");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdIsNull() {
            addCriterion("CMN_TANTO_CD is null");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdIsNotNull() {
            addCriterion("CMN_TANTO_CD is not null");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdEqualTo(String value) {
            addCriterion("CMN_TANTO_CD =", value, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdNotEqualTo(String value) {
            addCriterion("CMN_TANTO_CD <>", value, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdGreaterThan(String value) {
            addCriterion("CMN_TANTO_CD >", value, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdGreaterThanOrEqualTo(String value) {
            addCriterion("CMN_TANTO_CD >=", value, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdLessThan(String value) {
            addCriterion("CMN_TANTO_CD <", value, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdLessThanOrEqualTo(String value) {
            addCriterion("CMN_TANTO_CD <=", value, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdLike(String value) {
            addCriterion("CMN_TANTO_CD like", value, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdNotLike(String value) {
            addCriterion("CMN_TANTO_CD not like", value, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdIn(List<String> values) {
            addCriterion("CMN_TANTO_CD in", values, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdNotIn(List<String> values) {
            addCriterion("CMN_TANTO_CD not in", values, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdBetween(String value1, String value2) {
            addCriterion("CMN_TANTO_CD between", value1, value2, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdNotBetween(String value1, String value2) {
            addCriterion("CMN_TANTO_CD not between", value1, value2, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdIsNull() {
            addCriterion("CMN_TERM_ID is null");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdIsNotNull() {
            addCriterion("CMN_TERM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdEqualTo(String value) {
            addCriterion("CMN_TERM_ID =", value, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdNotEqualTo(String value) {
            addCriterion("CMN_TERM_ID <>", value, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdGreaterThan(String value) {
            addCriterion("CMN_TERM_ID >", value, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdGreaterThanOrEqualTo(String value) {
            addCriterion("CMN_TERM_ID >=", value, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdLessThan(String value) {
            addCriterion("CMN_TERM_ID <", value, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdLessThanOrEqualTo(String value) {
            addCriterion("CMN_TERM_ID <=", value, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdLike(String value) {
            addCriterion("CMN_TERM_ID like", value, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdNotLike(String value) {
            addCriterion("CMN_TERM_ID not like", value, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdIn(List<String> values) {
            addCriterion("CMN_TERM_ID in", values, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdNotIn(List<String> values) {
            addCriterion("CMN_TERM_ID not in", values, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdBetween(String value1, String value2) {
            addCriterion("CMN_TERM_ID between", value1, value2, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdNotBetween(String value1, String value2) {
            addCriterion("CMN_TERM_ID not between", value1, value2, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnInsddIsNull() {
            addCriterion("CMN_INSDD is null");
            return (Criteria) this;
        }

        public Criteria andCmnInsddIsNotNull() {
            addCriterion("CMN_INSDD is not null");
            return (Criteria) this;
        }

        public Criteria andCmnInsddEqualTo(String value) {
            addCriterion("CMN_INSDD =", value, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddNotEqualTo(String value) {
            addCriterion("CMN_INSDD <>", value, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddGreaterThan(String value) {
            addCriterion("CMN_INSDD >", value, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddGreaterThanOrEqualTo(String value) {
            addCriterion("CMN_INSDD >=", value, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddLessThan(String value) {
            addCriterion("CMN_INSDD <", value, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddLessThanOrEqualTo(String value) {
            addCriterion("CMN_INSDD <=", value, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddLike(String value) {
            addCriterion("CMN_INSDD like", value, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddNotLike(String value) {
            addCriterion("CMN_INSDD not like", value, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddIn(List<String> values) {
            addCriterion("CMN_INSDD in", values, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddNotIn(List<String> values) {
            addCriterion("CMN_INSDD not in", values, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddBetween(String value1, String value2) {
            addCriterion("CMN_INSDD between", value1, value2, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddNotBetween(String value1, String value2) {
            addCriterion("CMN_INSDD not between", value1, value2, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddIsNull() {
            addCriterion("CMN_UPDDD is null");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddIsNotNull() {
            addCriterion("CMN_UPDDD is not null");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddEqualTo(String value) {
            addCriterion("CMN_UPDDD =", value, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddNotEqualTo(String value) {
            addCriterion("CMN_UPDDD <>", value, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddGreaterThan(String value) {
            addCriterion("CMN_UPDDD >", value, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddGreaterThanOrEqualTo(String value) {
            addCriterion("CMN_UPDDD >=", value, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddLessThan(String value) {
            addCriterion("CMN_UPDDD <", value, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddLessThanOrEqualTo(String value) {
            addCriterion("CMN_UPDDD <=", value, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddLike(String value) {
            addCriterion("CMN_UPDDD like", value, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddNotLike(String value) {
            addCriterion("CMN_UPDDD not like", value, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddIn(List<String> values) {
            addCriterion("CMN_UPDDD in", values, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddNotIn(List<String> values) {
            addCriterion("CMN_UPDDD not in", values, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddBetween(String value1, String value2) {
            addCriterion("CMN_UPDDD between", value1, value2, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddNotBetween(String value1, String value2) {
            addCriterion("CMN_UPDDD not between", value1, value2, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeIsNull() {
            addCriterion("CMN_UPDTIME is null");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeIsNotNull() {
            addCriterion("CMN_UPDTIME is not null");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeEqualTo(String value) {
            addCriterion("CMN_UPDTIME =", value, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeNotEqualTo(String value) {
            addCriterion("CMN_UPDTIME <>", value, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeGreaterThan(String value) {
            addCriterion("CMN_UPDTIME >", value, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeGreaterThanOrEqualTo(String value) {
            addCriterion("CMN_UPDTIME >=", value, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeLessThan(String value) {
            addCriterion("CMN_UPDTIME <", value, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeLessThanOrEqualTo(String value) {
            addCriterion("CMN_UPDTIME <=", value, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeLike(String value) {
            addCriterion("CMN_UPDTIME like", value, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeNotLike(String value) {
            addCriterion("CMN_UPDTIME not like", value, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeIn(List<String> values) {
            addCriterion("CMN_UPDTIME in", values, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeNotIn(List<String> values) {
            addCriterion("CMN_UPDTIME not in", values, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeBetween(String value1, String value2) {
            addCriterion("CMN_UPDTIME between", value1, value2, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeNotBetween(String value1, String value2) {
            addCriterion("CMN_UPDTIME not between", value1, value2, "cmnUpdtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 22 09:53:12 JST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WEBMD.H050HATP
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}