package jp.co.necsoft.web_md.core.common.mybatis.dto;

import java.math.BigDecimal;

public class S042seno {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.DPY_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String dpyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.MESAI_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private Short mesaiNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.KAISYA_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String kaisyaCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.JIGYOUBU_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String jigyoubuCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.TEN_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String tenCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.KEY_SEQ_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private Short keySeqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.DPY_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String dpyKbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.REC_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String recKbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.BMN_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String bmnCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.MAIN_TORI_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String mainToriCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.NHN_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String nhnYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.TORIHIKI_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String torihikiCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.HAT_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String hatYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.NHN_YOTEI_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String nhnYoteiYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.RUI_KEIJO_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String ruiKeijoYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.FIRST_KAKUTEI_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String firstKakuteiYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.FIRST_TANTO_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String firstTantoCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.FIRST_TERM_ID
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String firstTermId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.LAST_KAKUTEI_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String lastKakuteiYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.LAST_TANTO_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String lastTantoCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.LAST_TERM_ID
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String lastTermId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.TAX_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String taxKbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.TAX_RITU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private BigDecimal taxRitu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.BIN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String bin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.CENTER_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String centerCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.ENTRY_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String entryKbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.ENTRY_PLACE
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String entryPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.KASAN_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String kasanKbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.DCTC_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String dctcKbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.SIR_GETUJI_YM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String sirGetujiYm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.SYORI_STS_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String syoriStsKbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.MOTO_DPY_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String motoDpyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.SEQ_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String seqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.TEKIYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String tekiyo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.ATUKAI_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String atukaiKbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.MKR_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String mkrCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.SHN_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String shnCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.PLU_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String pluKbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.CBNR_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String cbnrCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.SBNR_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String sbnrCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.KIKAKU_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String kikakuSu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.KIKAKU_TANI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String kikakuTani;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.IRI_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private Integer iriSu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.HATTYU_IRISU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private BigDecimal hattyuIrisu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.TANI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String tani;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.HAT_CASE_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private Integer hatCaseSu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.HAT_BARA_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private BigDecimal hatBaraSu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.HAT_GENK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private BigDecimal hatGenk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.HAT_BAIK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private BigDecimal hatBaik;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.HAT_GENK_KIN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private Long hatGenkKin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.HAT_BAIK_KIN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private Long hatBaikKin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.KEN_BARA_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private BigDecimal kenBaraSu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.KEN_GENK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private BigDecimal kenGenk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.KEN_BAIK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private BigDecimal kenBaik;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.KEN_GENK_KIN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private Long kenGenkKin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.KEN_BAIK_KIN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private Long kenBaikKin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.SANTI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String santi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.HAT_KIKAKU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String hatKikaku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.DAI_KIKAKU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String daiKikaku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.SIR_GENK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private BigDecimal sirGenk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.IDO_GENK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private BigDecimal idoGenk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.TEN_NM_A
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String tenNmA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.IDOMOTO_JIGYO_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String idomotoJigyoCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.IDOMOTO_TEN_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String idomotoTenCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.SANTI_CD1
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String santiCd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.SANTI_NM1
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String santiNm1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.SANTI_CD2
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String santiCd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.SANTI_NM2
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String santiNm2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.SANTI_CD3
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String santiCd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.SANTI_NM3
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String santiNm3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.HAT_KEITAI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String hatKeitai;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.GEN_CAT_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String genCatCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.GEN_BUN_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String genBunCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.KIEIYU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String kieiyu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.OKURI_FLG
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String okuriFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.TOKUBAI_FLG
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String tokubaiFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.SINKI_J_FLG
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String sinkiJFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.JIZEN_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String jizenNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.IRISU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private BigDecimal irisu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.NHN_TANI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String nhnTani;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.ZAIKO_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private BigDecimal zaikoSu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.JIZEN_HAT_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private BigDecimal jizenHatSu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.KINKY_HAT_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private BigDecimal kinkyHatSu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.BAIKTANK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private BigDecimal baiktank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.CMN_TANTO_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String cmnTantoCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.CMN_TERM_ID
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String cmnTermId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.CMN_INSDD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String cmnInsdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.CMN_UPDDD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String cmnUpddd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S042SENO.CMN_UPDTIME
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    private String cmnUpdtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.DPY_NO
     *
     * @return the value of WEBMD.S042SENO.DPY_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getDpyNo() {
        return dpyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.DPY_NO
     *
     * @param dpyNo the value for WEBMD.S042SENO.DPY_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setDpyNo(String dpyNo) {
        this.dpyNo = dpyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.MESAI_NO
     *
     * @return the value of WEBMD.S042SENO.MESAI_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public Short getMesaiNo() {
        return mesaiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.MESAI_NO
     *
     * @param mesaiNo the value for WEBMD.S042SENO.MESAI_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setMesaiNo(Short mesaiNo) {
        this.mesaiNo = mesaiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.KAISYA_CD
     *
     * @return the value of WEBMD.S042SENO.KAISYA_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getKaisyaCd() {
        return kaisyaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.KAISYA_CD
     *
     * @param kaisyaCd the value for WEBMD.S042SENO.KAISYA_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setKaisyaCd(String kaisyaCd) {
        this.kaisyaCd = kaisyaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.JIGYOUBU_CD
     *
     * @return the value of WEBMD.S042SENO.JIGYOUBU_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getJigyoubuCd() {
        return jigyoubuCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.JIGYOUBU_CD
     *
     * @param jigyoubuCd the value for WEBMD.S042SENO.JIGYOUBU_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setJigyoubuCd(String jigyoubuCd) {
        this.jigyoubuCd = jigyoubuCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.TEN_CD
     *
     * @return the value of WEBMD.S042SENO.TEN_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getTenCd() {
        return tenCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.TEN_CD
     *
     * @param tenCd the value for WEBMD.S042SENO.TEN_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setTenCd(String tenCd) {
        this.tenCd = tenCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.KEY_SEQ_NO
     *
     * @return the value of WEBMD.S042SENO.KEY_SEQ_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public Short getKeySeqNo() {
        return keySeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.KEY_SEQ_NO
     *
     * @param keySeqNo the value for WEBMD.S042SENO.KEY_SEQ_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setKeySeqNo(Short keySeqNo) {
        this.keySeqNo = keySeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.DPY_KBN
     *
     * @return the value of WEBMD.S042SENO.DPY_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getDpyKbn() {
        return dpyKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.DPY_KBN
     *
     * @param dpyKbn the value for WEBMD.S042SENO.DPY_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setDpyKbn(String dpyKbn) {
        this.dpyKbn = dpyKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.REC_KBN
     *
     * @return the value of WEBMD.S042SENO.REC_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getRecKbn() {
        return recKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.REC_KBN
     *
     * @param recKbn the value for WEBMD.S042SENO.REC_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setRecKbn(String recKbn) {
        this.recKbn = recKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.BMN_CD
     *
     * @return the value of WEBMD.S042SENO.BMN_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getBmnCd() {
        return bmnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.BMN_CD
     *
     * @param bmnCd the value for WEBMD.S042SENO.BMN_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setBmnCd(String bmnCd) {
        this.bmnCd = bmnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.MAIN_TORI_CD
     *
     * @return the value of WEBMD.S042SENO.MAIN_TORI_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getMainToriCd() {
        return mainToriCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.MAIN_TORI_CD
     *
     * @param mainToriCd the value for WEBMD.S042SENO.MAIN_TORI_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setMainToriCd(String mainToriCd) {
        this.mainToriCd = mainToriCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.NHN_YMD
     *
     * @return the value of WEBMD.S042SENO.NHN_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getNhnYmd() {
        return nhnYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.NHN_YMD
     *
     * @param nhnYmd the value for WEBMD.S042SENO.NHN_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setNhnYmd(String nhnYmd) {
        this.nhnYmd = nhnYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.TORIHIKI_CD
     *
     * @return the value of WEBMD.S042SENO.TORIHIKI_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getTorihikiCd() {
        return torihikiCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.TORIHIKI_CD
     *
     * @param torihikiCd the value for WEBMD.S042SENO.TORIHIKI_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setTorihikiCd(String torihikiCd) {
        this.torihikiCd = torihikiCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.HAT_YMD
     *
     * @return the value of WEBMD.S042SENO.HAT_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getHatYmd() {
        return hatYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.HAT_YMD
     *
     * @param hatYmd the value for WEBMD.S042SENO.HAT_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setHatYmd(String hatYmd) {
        this.hatYmd = hatYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.NHN_YOTEI_YMD
     *
     * @return the value of WEBMD.S042SENO.NHN_YOTEI_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getNhnYoteiYmd() {
        return nhnYoteiYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.NHN_YOTEI_YMD
     *
     * @param nhnYoteiYmd the value for WEBMD.S042SENO.NHN_YOTEI_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setNhnYoteiYmd(String nhnYoteiYmd) {
        this.nhnYoteiYmd = nhnYoteiYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.RUI_KEIJO_YMD
     *
     * @return the value of WEBMD.S042SENO.RUI_KEIJO_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getRuiKeijoYmd() {
        return ruiKeijoYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.RUI_KEIJO_YMD
     *
     * @param ruiKeijoYmd the value for WEBMD.S042SENO.RUI_KEIJO_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setRuiKeijoYmd(String ruiKeijoYmd) {
        this.ruiKeijoYmd = ruiKeijoYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.FIRST_KAKUTEI_YMD
     *
     * @return the value of WEBMD.S042SENO.FIRST_KAKUTEI_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getFirstKakuteiYmd() {
        return firstKakuteiYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.FIRST_KAKUTEI_YMD
     *
     * @param firstKakuteiYmd the value for WEBMD.S042SENO.FIRST_KAKUTEI_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setFirstKakuteiYmd(String firstKakuteiYmd) {
        this.firstKakuteiYmd = firstKakuteiYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.FIRST_TANTO_CD
     *
     * @return the value of WEBMD.S042SENO.FIRST_TANTO_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getFirstTantoCd() {
        return firstTantoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.FIRST_TANTO_CD
     *
     * @param firstTantoCd the value for WEBMD.S042SENO.FIRST_TANTO_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setFirstTantoCd(String firstTantoCd) {
        this.firstTantoCd = firstTantoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.FIRST_TERM_ID
     *
     * @return the value of WEBMD.S042SENO.FIRST_TERM_ID
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getFirstTermId() {
        return firstTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.FIRST_TERM_ID
     *
     * @param firstTermId the value for WEBMD.S042SENO.FIRST_TERM_ID
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setFirstTermId(String firstTermId) {
        this.firstTermId = firstTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.LAST_KAKUTEI_YMD
     *
     * @return the value of WEBMD.S042SENO.LAST_KAKUTEI_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getLastKakuteiYmd() {
        return lastKakuteiYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.LAST_KAKUTEI_YMD
     *
     * @param lastKakuteiYmd the value for WEBMD.S042SENO.LAST_KAKUTEI_YMD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setLastKakuteiYmd(String lastKakuteiYmd) {
        this.lastKakuteiYmd = lastKakuteiYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.LAST_TANTO_CD
     *
     * @return the value of WEBMD.S042SENO.LAST_TANTO_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getLastTantoCd() {
        return lastTantoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.LAST_TANTO_CD
     *
     * @param lastTantoCd the value for WEBMD.S042SENO.LAST_TANTO_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setLastTantoCd(String lastTantoCd) {
        this.lastTantoCd = lastTantoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.LAST_TERM_ID
     *
     * @return the value of WEBMD.S042SENO.LAST_TERM_ID
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getLastTermId() {
        return lastTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.LAST_TERM_ID
     *
     * @param lastTermId the value for WEBMD.S042SENO.LAST_TERM_ID
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setLastTermId(String lastTermId) {
        this.lastTermId = lastTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.TAX_KBN
     *
     * @return the value of WEBMD.S042SENO.TAX_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getTaxKbn() {
        return taxKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.TAX_KBN
     *
     * @param taxKbn the value for WEBMD.S042SENO.TAX_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setTaxKbn(String taxKbn) {
        this.taxKbn = taxKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.TAX_RITU
     *
     * @return the value of WEBMD.S042SENO.TAX_RITU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public BigDecimal getTaxRitu() {
        return taxRitu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.TAX_RITU
     *
     * @param taxRitu the value for WEBMD.S042SENO.TAX_RITU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setTaxRitu(BigDecimal taxRitu) {
        this.taxRitu = taxRitu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.BIN
     *
     * @return the value of WEBMD.S042SENO.BIN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getBin() {
        return bin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.BIN
     *
     * @param bin the value for WEBMD.S042SENO.BIN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setBin(String bin) {
        this.bin = bin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.CENTER_CD
     *
     * @return the value of WEBMD.S042SENO.CENTER_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getCenterCd() {
        return centerCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.CENTER_CD
     *
     * @param centerCd the value for WEBMD.S042SENO.CENTER_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setCenterCd(String centerCd) {
        this.centerCd = centerCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.ENTRY_KBN
     *
     * @return the value of WEBMD.S042SENO.ENTRY_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getEntryKbn() {
        return entryKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.ENTRY_KBN
     *
     * @param entryKbn the value for WEBMD.S042SENO.ENTRY_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setEntryKbn(String entryKbn) {
        this.entryKbn = entryKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.ENTRY_PLACE
     *
     * @return the value of WEBMD.S042SENO.ENTRY_PLACE
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getEntryPlace() {
        return entryPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.ENTRY_PLACE
     *
     * @param entryPlace the value for WEBMD.S042SENO.ENTRY_PLACE
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setEntryPlace(String entryPlace) {
        this.entryPlace = entryPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.KASAN_KBN
     *
     * @return the value of WEBMD.S042SENO.KASAN_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getKasanKbn() {
        return kasanKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.KASAN_KBN
     *
     * @param kasanKbn the value for WEBMD.S042SENO.KASAN_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setKasanKbn(String kasanKbn) {
        this.kasanKbn = kasanKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.DCTC_KBN
     *
     * @return the value of WEBMD.S042SENO.DCTC_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getDctcKbn() {
        return dctcKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.DCTC_KBN
     *
     * @param dctcKbn the value for WEBMD.S042SENO.DCTC_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setDctcKbn(String dctcKbn) {
        this.dctcKbn = dctcKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.SIR_GETUJI_YM
     *
     * @return the value of WEBMD.S042SENO.SIR_GETUJI_YM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getSirGetujiYm() {
        return sirGetujiYm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.SIR_GETUJI_YM
     *
     * @param sirGetujiYm the value for WEBMD.S042SENO.SIR_GETUJI_YM
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setSirGetujiYm(String sirGetujiYm) {
        this.sirGetujiYm = sirGetujiYm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.SYORI_STS_KBN
     *
     * @return the value of WEBMD.S042SENO.SYORI_STS_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getSyoriStsKbn() {
        return syoriStsKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.SYORI_STS_KBN
     *
     * @param syoriStsKbn the value for WEBMD.S042SENO.SYORI_STS_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setSyoriStsKbn(String syoriStsKbn) {
        this.syoriStsKbn = syoriStsKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.MOTO_DPY_NO
     *
     * @return the value of WEBMD.S042SENO.MOTO_DPY_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getMotoDpyNo() {
        return motoDpyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.MOTO_DPY_NO
     *
     * @param motoDpyNo the value for WEBMD.S042SENO.MOTO_DPY_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setMotoDpyNo(String motoDpyNo) {
        this.motoDpyNo = motoDpyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.SEQ_NO
     *
     * @return the value of WEBMD.S042SENO.SEQ_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.SEQ_NO
     *
     * @param seqNo the value for WEBMD.S042SENO.SEQ_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.TEKIYO
     *
     * @return the value of WEBMD.S042SENO.TEKIYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getTekiyo() {
        return tekiyo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.TEKIYO
     *
     * @param tekiyo the value for WEBMD.S042SENO.TEKIYO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setTekiyo(String tekiyo) {
        this.tekiyo = tekiyo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.ATUKAI_KBN
     *
     * @return the value of WEBMD.S042SENO.ATUKAI_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getAtukaiKbn() {
        return atukaiKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.ATUKAI_KBN
     *
     * @param atukaiKbn the value for WEBMD.S042SENO.ATUKAI_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setAtukaiKbn(String atukaiKbn) {
        this.atukaiKbn = atukaiKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.MKR_CD
     *
     * @return the value of WEBMD.S042SENO.MKR_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getMkrCd() {
        return mkrCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.MKR_CD
     *
     * @param mkrCd the value for WEBMD.S042SENO.MKR_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setMkrCd(String mkrCd) {
        this.mkrCd = mkrCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.SHN_CD
     *
     * @return the value of WEBMD.S042SENO.SHN_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getShnCd() {
        return shnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.SHN_CD
     *
     * @param shnCd the value for WEBMD.S042SENO.SHN_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setShnCd(String shnCd) {
        this.shnCd = shnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.PLU_KBN
     *
     * @return the value of WEBMD.S042SENO.PLU_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getPluKbn() {
        return pluKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.PLU_KBN
     *
     * @param pluKbn the value for WEBMD.S042SENO.PLU_KBN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setPluKbn(String pluKbn) {
        this.pluKbn = pluKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.CBNR_CD
     *
     * @return the value of WEBMD.S042SENO.CBNR_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getCbnrCd() {
        return cbnrCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.CBNR_CD
     *
     * @param cbnrCd the value for WEBMD.S042SENO.CBNR_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setCbnrCd(String cbnrCd) {
        this.cbnrCd = cbnrCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.SBNR_CD
     *
     * @return the value of WEBMD.S042SENO.SBNR_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getSbnrCd() {
        return sbnrCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.SBNR_CD
     *
     * @param sbnrCd the value for WEBMD.S042SENO.SBNR_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setSbnrCd(String sbnrCd) {
        this.sbnrCd = sbnrCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.KIKAKU_SU
     *
     * @return the value of WEBMD.S042SENO.KIKAKU_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getKikakuSu() {
        return kikakuSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.KIKAKU_SU
     *
     * @param kikakuSu the value for WEBMD.S042SENO.KIKAKU_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setKikakuSu(String kikakuSu) {
        this.kikakuSu = kikakuSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.KIKAKU_TANI
     *
     * @return the value of WEBMD.S042SENO.KIKAKU_TANI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getKikakuTani() {
        return kikakuTani;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.KIKAKU_TANI
     *
     * @param kikakuTani the value for WEBMD.S042SENO.KIKAKU_TANI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setKikakuTani(String kikakuTani) {
        this.kikakuTani = kikakuTani;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.IRI_SU
     *
     * @return the value of WEBMD.S042SENO.IRI_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public Integer getIriSu() {
        return iriSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.IRI_SU
     *
     * @param iriSu the value for WEBMD.S042SENO.IRI_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setIriSu(Integer iriSu) {
        this.iriSu = iriSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.HATTYU_IRISU
     *
     * @return the value of WEBMD.S042SENO.HATTYU_IRISU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public BigDecimal getHattyuIrisu() {
        return hattyuIrisu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.HATTYU_IRISU
     *
     * @param hattyuIrisu the value for WEBMD.S042SENO.HATTYU_IRISU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setHattyuIrisu(BigDecimal hattyuIrisu) {
        this.hattyuIrisu = hattyuIrisu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.TANI
     *
     * @return the value of WEBMD.S042SENO.TANI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getTani() {
        return tani;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.TANI
     *
     * @param tani the value for WEBMD.S042SENO.TANI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setTani(String tani) {
        this.tani = tani;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.HAT_CASE_SU
     *
     * @return the value of WEBMD.S042SENO.HAT_CASE_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public Integer getHatCaseSu() {
        return hatCaseSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.HAT_CASE_SU
     *
     * @param hatCaseSu the value for WEBMD.S042SENO.HAT_CASE_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setHatCaseSu(Integer hatCaseSu) {
        this.hatCaseSu = hatCaseSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.HAT_BARA_SU
     *
     * @return the value of WEBMD.S042SENO.HAT_BARA_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public BigDecimal getHatBaraSu() {
        return hatBaraSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.HAT_BARA_SU
     *
     * @param hatBaraSu the value for WEBMD.S042SENO.HAT_BARA_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setHatBaraSu(BigDecimal hatBaraSu) {
        this.hatBaraSu = hatBaraSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.HAT_GENK
     *
     * @return the value of WEBMD.S042SENO.HAT_GENK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public BigDecimal getHatGenk() {
        return hatGenk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.HAT_GENK
     *
     * @param hatGenk the value for WEBMD.S042SENO.HAT_GENK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setHatGenk(BigDecimal hatGenk) {
        this.hatGenk = hatGenk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.HAT_BAIK
     *
     * @return the value of WEBMD.S042SENO.HAT_BAIK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public BigDecimal getHatBaik() {
        return hatBaik;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.HAT_BAIK
     *
     * @param hatBaik the value for WEBMD.S042SENO.HAT_BAIK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setHatBaik(BigDecimal hatBaik) {
        this.hatBaik = hatBaik;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.HAT_GENK_KIN
     *
     * @return the value of WEBMD.S042SENO.HAT_GENK_KIN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public Long getHatGenkKin() {
        return hatGenkKin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.HAT_GENK_KIN
     *
     * @param hatGenkKin the value for WEBMD.S042SENO.HAT_GENK_KIN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setHatGenkKin(Long hatGenkKin) {
        this.hatGenkKin = hatGenkKin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.HAT_BAIK_KIN
     *
     * @return the value of WEBMD.S042SENO.HAT_BAIK_KIN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public Long getHatBaikKin() {
        return hatBaikKin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.HAT_BAIK_KIN
     *
     * @param hatBaikKin the value for WEBMD.S042SENO.HAT_BAIK_KIN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setHatBaikKin(Long hatBaikKin) {
        this.hatBaikKin = hatBaikKin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.KEN_BARA_SU
     *
     * @return the value of WEBMD.S042SENO.KEN_BARA_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public BigDecimal getKenBaraSu() {
        return kenBaraSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.KEN_BARA_SU
     *
     * @param kenBaraSu the value for WEBMD.S042SENO.KEN_BARA_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setKenBaraSu(BigDecimal kenBaraSu) {
        this.kenBaraSu = kenBaraSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.KEN_GENK
     *
     * @return the value of WEBMD.S042SENO.KEN_GENK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public BigDecimal getKenGenk() {
        return kenGenk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.KEN_GENK
     *
     * @param kenGenk the value for WEBMD.S042SENO.KEN_GENK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setKenGenk(BigDecimal kenGenk) {
        this.kenGenk = kenGenk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.KEN_BAIK
     *
     * @return the value of WEBMD.S042SENO.KEN_BAIK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public BigDecimal getKenBaik() {
        return kenBaik;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.KEN_BAIK
     *
     * @param kenBaik the value for WEBMD.S042SENO.KEN_BAIK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setKenBaik(BigDecimal kenBaik) {
        this.kenBaik = kenBaik;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.KEN_GENK_KIN
     *
     * @return the value of WEBMD.S042SENO.KEN_GENK_KIN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public Long getKenGenkKin() {
        return kenGenkKin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.KEN_GENK_KIN
     *
     * @param kenGenkKin the value for WEBMD.S042SENO.KEN_GENK_KIN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setKenGenkKin(Long kenGenkKin) {
        this.kenGenkKin = kenGenkKin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.KEN_BAIK_KIN
     *
     * @return the value of WEBMD.S042SENO.KEN_BAIK_KIN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public Long getKenBaikKin() {
        return kenBaikKin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.KEN_BAIK_KIN
     *
     * @param kenBaikKin the value for WEBMD.S042SENO.KEN_BAIK_KIN
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setKenBaikKin(Long kenBaikKin) {
        this.kenBaikKin = kenBaikKin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.SANTI
     *
     * @return the value of WEBMD.S042SENO.SANTI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getSanti() {
        return santi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.SANTI
     *
     * @param santi the value for WEBMD.S042SENO.SANTI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setSanti(String santi) {
        this.santi = santi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.HAT_KIKAKU
     *
     * @return the value of WEBMD.S042SENO.HAT_KIKAKU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getHatKikaku() {
        return hatKikaku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.HAT_KIKAKU
     *
     * @param hatKikaku the value for WEBMD.S042SENO.HAT_KIKAKU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setHatKikaku(String hatKikaku) {
        this.hatKikaku = hatKikaku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.DAI_KIKAKU
     *
     * @return the value of WEBMD.S042SENO.DAI_KIKAKU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getDaiKikaku() {
        return daiKikaku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.DAI_KIKAKU
     *
     * @param daiKikaku the value for WEBMD.S042SENO.DAI_KIKAKU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setDaiKikaku(String daiKikaku) {
        this.daiKikaku = daiKikaku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.SIR_GENK
     *
     * @return the value of WEBMD.S042SENO.SIR_GENK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public BigDecimal getSirGenk() {
        return sirGenk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.SIR_GENK
     *
     * @param sirGenk the value for WEBMD.S042SENO.SIR_GENK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setSirGenk(BigDecimal sirGenk) {
        this.sirGenk = sirGenk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.IDO_GENK
     *
     * @return the value of WEBMD.S042SENO.IDO_GENK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public BigDecimal getIdoGenk() {
        return idoGenk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.IDO_GENK
     *
     * @param idoGenk the value for WEBMD.S042SENO.IDO_GENK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setIdoGenk(BigDecimal idoGenk) {
        this.idoGenk = idoGenk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.TEN_NM_A
     *
     * @return the value of WEBMD.S042SENO.TEN_NM_A
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getTenNmA() {
        return tenNmA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.TEN_NM_A
     *
     * @param tenNmA the value for WEBMD.S042SENO.TEN_NM_A
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setTenNmA(String tenNmA) {
        this.tenNmA = tenNmA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.IDOMOTO_JIGYO_CD
     *
     * @return the value of WEBMD.S042SENO.IDOMOTO_JIGYO_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getIdomotoJigyoCd() {
        return idomotoJigyoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.IDOMOTO_JIGYO_CD
     *
     * @param idomotoJigyoCd the value for WEBMD.S042SENO.IDOMOTO_JIGYO_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setIdomotoJigyoCd(String idomotoJigyoCd) {
        this.idomotoJigyoCd = idomotoJigyoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.IDOMOTO_TEN_CD
     *
     * @return the value of WEBMD.S042SENO.IDOMOTO_TEN_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getIdomotoTenCd() {
        return idomotoTenCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.IDOMOTO_TEN_CD
     *
     * @param idomotoTenCd the value for WEBMD.S042SENO.IDOMOTO_TEN_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setIdomotoTenCd(String idomotoTenCd) {
        this.idomotoTenCd = idomotoTenCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.SANTI_CD1
     *
     * @return the value of WEBMD.S042SENO.SANTI_CD1
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getSantiCd1() {
        return santiCd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.SANTI_CD1
     *
     * @param santiCd1 the value for WEBMD.S042SENO.SANTI_CD1
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setSantiCd1(String santiCd1) {
        this.santiCd1 = santiCd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.SANTI_NM1
     *
     * @return the value of WEBMD.S042SENO.SANTI_NM1
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getSantiNm1() {
        return santiNm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.SANTI_NM1
     *
     * @param santiNm1 the value for WEBMD.S042SENO.SANTI_NM1
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setSantiNm1(String santiNm1) {
        this.santiNm1 = santiNm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.SANTI_CD2
     *
     * @return the value of WEBMD.S042SENO.SANTI_CD2
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getSantiCd2() {
        return santiCd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.SANTI_CD2
     *
     * @param santiCd2 the value for WEBMD.S042SENO.SANTI_CD2
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setSantiCd2(String santiCd2) {
        this.santiCd2 = santiCd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.SANTI_NM2
     *
     * @return the value of WEBMD.S042SENO.SANTI_NM2
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getSantiNm2() {
        return santiNm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.SANTI_NM2
     *
     * @param santiNm2 the value for WEBMD.S042SENO.SANTI_NM2
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setSantiNm2(String santiNm2) {
        this.santiNm2 = santiNm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.SANTI_CD3
     *
     * @return the value of WEBMD.S042SENO.SANTI_CD3
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getSantiCd3() {
        return santiCd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.SANTI_CD3
     *
     * @param santiCd3 the value for WEBMD.S042SENO.SANTI_CD3
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setSantiCd3(String santiCd3) {
        this.santiCd3 = santiCd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.SANTI_NM3
     *
     * @return the value of WEBMD.S042SENO.SANTI_NM3
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getSantiNm3() {
        return santiNm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.SANTI_NM3
     *
     * @param santiNm3 the value for WEBMD.S042SENO.SANTI_NM3
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setSantiNm3(String santiNm3) {
        this.santiNm3 = santiNm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.HAT_KEITAI
     *
     * @return the value of WEBMD.S042SENO.HAT_KEITAI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getHatKeitai() {
        return hatKeitai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.HAT_KEITAI
     *
     * @param hatKeitai the value for WEBMD.S042SENO.HAT_KEITAI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setHatKeitai(String hatKeitai) {
        this.hatKeitai = hatKeitai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.GEN_CAT_CD
     *
     * @return the value of WEBMD.S042SENO.GEN_CAT_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getGenCatCd() {
        return genCatCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.GEN_CAT_CD
     *
     * @param genCatCd the value for WEBMD.S042SENO.GEN_CAT_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setGenCatCd(String genCatCd) {
        this.genCatCd = genCatCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.GEN_BUN_CD
     *
     * @return the value of WEBMD.S042SENO.GEN_BUN_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getGenBunCd() {
        return genBunCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.GEN_BUN_CD
     *
     * @param genBunCd the value for WEBMD.S042SENO.GEN_BUN_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setGenBunCd(String genBunCd) {
        this.genBunCd = genBunCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.KIEIYU
     *
     * @return the value of WEBMD.S042SENO.KIEIYU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getKieiyu() {
        return kieiyu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.KIEIYU
     *
     * @param kieiyu the value for WEBMD.S042SENO.KIEIYU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setKieiyu(String kieiyu) {
        this.kieiyu = kieiyu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.OKURI_FLG
     *
     * @return the value of WEBMD.S042SENO.OKURI_FLG
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getOkuriFlg() {
        return okuriFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.OKURI_FLG
     *
     * @param okuriFlg the value for WEBMD.S042SENO.OKURI_FLG
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setOkuriFlg(String okuriFlg) {
        this.okuriFlg = okuriFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.TOKUBAI_FLG
     *
     * @return the value of WEBMD.S042SENO.TOKUBAI_FLG
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getTokubaiFlg() {
        return tokubaiFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.TOKUBAI_FLG
     *
     * @param tokubaiFlg the value for WEBMD.S042SENO.TOKUBAI_FLG
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setTokubaiFlg(String tokubaiFlg) {
        this.tokubaiFlg = tokubaiFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.SINKI_J_FLG
     *
     * @return the value of WEBMD.S042SENO.SINKI_J_FLG
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getSinkiJFlg() {
        return sinkiJFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.SINKI_J_FLG
     *
     * @param sinkiJFlg the value for WEBMD.S042SENO.SINKI_J_FLG
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setSinkiJFlg(String sinkiJFlg) {
        this.sinkiJFlg = sinkiJFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.JIZEN_NO
     *
     * @return the value of WEBMD.S042SENO.JIZEN_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getJizenNo() {
        return jizenNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.JIZEN_NO
     *
     * @param jizenNo the value for WEBMD.S042SENO.JIZEN_NO
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setJizenNo(String jizenNo) {
        this.jizenNo = jizenNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.IRISU
     *
     * @return the value of WEBMD.S042SENO.IRISU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public BigDecimal getIrisu() {
        return irisu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.IRISU
     *
     * @param irisu the value for WEBMD.S042SENO.IRISU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setIrisu(BigDecimal irisu) {
        this.irisu = irisu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.NHN_TANI
     *
     * @return the value of WEBMD.S042SENO.NHN_TANI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getNhnTani() {
        return nhnTani;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.NHN_TANI
     *
     * @param nhnTani the value for WEBMD.S042SENO.NHN_TANI
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setNhnTani(String nhnTani) {
        this.nhnTani = nhnTani;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.ZAIKO_SU
     *
     * @return the value of WEBMD.S042SENO.ZAIKO_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public BigDecimal getZaikoSu() {
        return zaikoSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.ZAIKO_SU
     *
     * @param zaikoSu the value for WEBMD.S042SENO.ZAIKO_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setZaikoSu(BigDecimal zaikoSu) {
        this.zaikoSu = zaikoSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.JIZEN_HAT_SU
     *
     * @return the value of WEBMD.S042SENO.JIZEN_HAT_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public BigDecimal getJizenHatSu() {
        return jizenHatSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.JIZEN_HAT_SU
     *
     * @param jizenHatSu the value for WEBMD.S042SENO.JIZEN_HAT_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setJizenHatSu(BigDecimal jizenHatSu) {
        this.jizenHatSu = jizenHatSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.KINKY_HAT_SU
     *
     * @return the value of WEBMD.S042SENO.KINKY_HAT_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public BigDecimal getKinkyHatSu() {
        return kinkyHatSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.KINKY_HAT_SU
     *
     * @param kinkyHatSu the value for WEBMD.S042SENO.KINKY_HAT_SU
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setKinkyHatSu(BigDecimal kinkyHatSu) {
        this.kinkyHatSu = kinkyHatSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.BAIKTANK
     *
     * @return the value of WEBMD.S042SENO.BAIKTANK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public BigDecimal getBaiktank() {
        return baiktank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.BAIKTANK
     *
     * @param baiktank the value for WEBMD.S042SENO.BAIKTANK
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setBaiktank(BigDecimal baiktank) {
        this.baiktank = baiktank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.CMN_TANTO_CD
     *
     * @return the value of WEBMD.S042SENO.CMN_TANTO_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getCmnTantoCd() {
        return cmnTantoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.CMN_TANTO_CD
     *
     * @param cmnTantoCd the value for WEBMD.S042SENO.CMN_TANTO_CD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setCmnTantoCd(String cmnTantoCd) {
        this.cmnTantoCd = cmnTantoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.CMN_TERM_ID
     *
     * @return the value of WEBMD.S042SENO.CMN_TERM_ID
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getCmnTermId() {
        return cmnTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.CMN_TERM_ID
     *
     * @param cmnTermId the value for WEBMD.S042SENO.CMN_TERM_ID
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setCmnTermId(String cmnTermId) {
        this.cmnTermId = cmnTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.CMN_INSDD
     *
     * @return the value of WEBMD.S042SENO.CMN_INSDD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getCmnInsdd() {
        return cmnInsdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.CMN_INSDD
     *
     * @param cmnInsdd the value for WEBMD.S042SENO.CMN_INSDD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setCmnInsdd(String cmnInsdd) {
        this.cmnInsdd = cmnInsdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.CMN_UPDDD
     *
     * @return the value of WEBMD.S042SENO.CMN_UPDDD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getCmnUpddd() {
        return cmnUpddd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.CMN_UPDDD
     *
     * @param cmnUpddd the value for WEBMD.S042SENO.CMN_UPDDD
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setCmnUpddd(String cmnUpddd) {
        this.cmnUpddd = cmnUpddd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S042SENO.CMN_UPDTIME
     *
     * @return the value of WEBMD.S042SENO.CMN_UPDTIME
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public String getCmnUpdtime() {
        return cmnUpdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S042SENO.CMN_UPDTIME
     *
     * @param cmnUpdtime the value for WEBMD.S042SENO.CMN_UPDTIME
     *
     * @mbggenerated Wed Jan 22 09:53:12 JST 2014
     */
    public void setCmnUpdtime(String cmnUpdtime) {
        this.cmnUpdtime = cmnUpdtime;
    }
}