package jp.co.necsoft.web_md.core.common.mybatis.dto;

public class S048frih {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.DPY_NO
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String dpyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.DPY_KBN
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String dpyKbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.IN_TENPO_CD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String inTenpoCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.IN_BMN_CD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String inBmnCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.OUT_TENPO_CD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String outTenpoCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.OUT_BMN_CD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String outBmnCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.MSAI_SU
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private Short msaiSu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.MESAI_NO_01
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private Short mesaiNo01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_01
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String kppinRiyuKbn01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.MESAI_NO_02
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private Short mesaiNo02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_02
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String kppinRiyuKbn02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.MESAI_NO_03
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private Short mesaiNo03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_03
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String kppinRiyuKbn03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.MESAI_NO_04
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private Short mesaiNo04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_04
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String kppinRiyuKbn04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.MESAI_NO_05
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private Short mesaiNo05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_05
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String kppinRiyuKbn05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.MESAI_NO_06
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private Short mesaiNo06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_06
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String kppinRiyuKbn06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.MESAI_NO_07
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private Short mesaiNo07;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_07
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String kppinRiyuKbn07;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.MESAI_NO_08
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private Short mesaiNo08;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_08
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String kppinRiyuKbn08;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.MESAI_NO_09
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private Short mesaiNo09;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_09
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String kppinRiyuKbn09;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.MESAI_NO_10
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private Short mesaiNo10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_10
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String kppinRiyuKbn10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.CMN_TANTO_CD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String cmnTantoCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.CMN_TERM_ID
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String cmnTermId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.CMN_INSDD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String cmnInsdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.CMN_UPDDD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String cmnUpddd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMDTEST.S048FRIH.CMN_UPDTIME
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    private String cmnUpdtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.DPY_NO
     *
     * @return the value of WEBMDTEST.S048FRIH.DPY_NO
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getDpyNo() {
        return dpyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.DPY_NO
     *
     * @param dpyNo the value for WEBMDTEST.S048FRIH.DPY_NO
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setDpyNo(String dpyNo) {
        this.dpyNo = dpyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.DPY_KBN
     *
     * @return the value of WEBMDTEST.S048FRIH.DPY_KBN
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getDpyKbn() {
        return dpyKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.DPY_KBN
     *
     * @param dpyKbn the value for WEBMDTEST.S048FRIH.DPY_KBN
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setDpyKbn(String dpyKbn) {
        this.dpyKbn = dpyKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.IN_TENPO_CD
     *
     * @return the value of WEBMDTEST.S048FRIH.IN_TENPO_CD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getInTenpoCd() {
        return inTenpoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.IN_TENPO_CD
     *
     * @param inTenpoCd the value for WEBMDTEST.S048FRIH.IN_TENPO_CD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setInTenpoCd(String inTenpoCd) {
        this.inTenpoCd = inTenpoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.IN_BMN_CD
     *
     * @return the value of WEBMDTEST.S048FRIH.IN_BMN_CD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getInBmnCd() {
        return inBmnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.IN_BMN_CD
     *
     * @param inBmnCd the value for WEBMDTEST.S048FRIH.IN_BMN_CD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setInBmnCd(String inBmnCd) {
        this.inBmnCd = inBmnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.OUT_TENPO_CD
     *
     * @return the value of WEBMDTEST.S048FRIH.OUT_TENPO_CD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getOutTenpoCd() {
        return outTenpoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.OUT_TENPO_CD
     *
     * @param outTenpoCd the value for WEBMDTEST.S048FRIH.OUT_TENPO_CD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setOutTenpoCd(String outTenpoCd) {
        this.outTenpoCd = outTenpoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.OUT_BMN_CD
     *
     * @return the value of WEBMDTEST.S048FRIH.OUT_BMN_CD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getOutBmnCd() {
        return outBmnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.OUT_BMN_CD
     *
     * @param outBmnCd the value for WEBMDTEST.S048FRIH.OUT_BMN_CD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setOutBmnCd(String outBmnCd) {
        this.outBmnCd = outBmnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.MSAI_SU
     *
     * @return the value of WEBMDTEST.S048FRIH.MSAI_SU
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public Short getMsaiSu() {
        return msaiSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.MSAI_SU
     *
     * @param msaiSu the value for WEBMDTEST.S048FRIH.MSAI_SU
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setMsaiSu(Short msaiSu) {
        this.msaiSu = msaiSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_01
     *
     * @return the value of WEBMDTEST.S048FRIH.MESAI_NO_01
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public Short getMesaiNo01() {
        return mesaiNo01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_01
     *
     * @param mesaiNo01 the value for WEBMDTEST.S048FRIH.MESAI_NO_01
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setMesaiNo01(Short mesaiNo01) {
        this.mesaiNo01 = mesaiNo01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_01
     *
     * @return the value of WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_01
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getKppinRiyuKbn01() {
        return kppinRiyuKbn01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_01
     *
     * @param kppinRiyuKbn01 the value for WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_01
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setKppinRiyuKbn01(String kppinRiyuKbn01) {
        this.kppinRiyuKbn01 = kppinRiyuKbn01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_02
     *
     * @return the value of WEBMDTEST.S048FRIH.MESAI_NO_02
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public Short getMesaiNo02() {
        return mesaiNo02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_02
     *
     * @param mesaiNo02 the value for WEBMDTEST.S048FRIH.MESAI_NO_02
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setMesaiNo02(Short mesaiNo02) {
        this.mesaiNo02 = mesaiNo02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_02
     *
     * @return the value of WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_02
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getKppinRiyuKbn02() {
        return kppinRiyuKbn02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_02
     *
     * @param kppinRiyuKbn02 the value for WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_02
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setKppinRiyuKbn02(String kppinRiyuKbn02) {
        this.kppinRiyuKbn02 = kppinRiyuKbn02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_03
     *
     * @return the value of WEBMDTEST.S048FRIH.MESAI_NO_03
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public Short getMesaiNo03() {
        return mesaiNo03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_03
     *
     * @param mesaiNo03 the value for WEBMDTEST.S048FRIH.MESAI_NO_03
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setMesaiNo03(Short mesaiNo03) {
        this.mesaiNo03 = mesaiNo03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_03
     *
     * @return the value of WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_03
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getKppinRiyuKbn03() {
        return kppinRiyuKbn03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_03
     *
     * @param kppinRiyuKbn03 the value for WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_03
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setKppinRiyuKbn03(String kppinRiyuKbn03) {
        this.kppinRiyuKbn03 = kppinRiyuKbn03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_04
     *
     * @return the value of WEBMDTEST.S048FRIH.MESAI_NO_04
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public Short getMesaiNo04() {
        return mesaiNo04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_04
     *
     * @param mesaiNo04 the value for WEBMDTEST.S048FRIH.MESAI_NO_04
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setMesaiNo04(Short mesaiNo04) {
        this.mesaiNo04 = mesaiNo04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_04
     *
     * @return the value of WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_04
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getKppinRiyuKbn04() {
        return kppinRiyuKbn04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_04
     *
     * @param kppinRiyuKbn04 the value for WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_04
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setKppinRiyuKbn04(String kppinRiyuKbn04) {
        this.kppinRiyuKbn04 = kppinRiyuKbn04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_05
     *
     * @return the value of WEBMDTEST.S048FRIH.MESAI_NO_05
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public Short getMesaiNo05() {
        return mesaiNo05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_05
     *
     * @param mesaiNo05 the value for WEBMDTEST.S048FRIH.MESAI_NO_05
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setMesaiNo05(Short mesaiNo05) {
        this.mesaiNo05 = mesaiNo05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_05
     *
     * @return the value of WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_05
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getKppinRiyuKbn05() {
        return kppinRiyuKbn05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_05
     *
     * @param kppinRiyuKbn05 the value for WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_05
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setKppinRiyuKbn05(String kppinRiyuKbn05) {
        this.kppinRiyuKbn05 = kppinRiyuKbn05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_06
     *
     * @return the value of WEBMDTEST.S048FRIH.MESAI_NO_06
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public Short getMesaiNo06() {
        return mesaiNo06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_06
     *
     * @param mesaiNo06 the value for WEBMDTEST.S048FRIH.MESAI_NO_06
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setMesaiNo06(Short mesaiNo06) {
        this.mesaiNo06 = mesaiNo06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_06
     *
     * @return the value of WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_06
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getKppinRiyuKbn06() {
        return kppinRiyuKbn06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_06
     *
     * @param kppinRiyuKbn06 the value for WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_06
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setKppinRiyuKbn06(String kppinRiyuKbn06) {
        this.kppinRiyuKbn06 = kppinRiyuKbn06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_07
     *
     * @return the value of WEBMDTEST.S048FRIH.MESAI_NO_07
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public Short getMesaiNo07() {
        return mesaiNo07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_07
     *
     * @param mesaiNo07 the value for WEBMDTEST.S048FRIH.MESAI_NO_07
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setMesaiNo07(Short mesaiNo07) {
        this.mesaiNo07 = mesaiNo07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_07
     *
     * @return the value of WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_07
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getKppinRiyuKbn07() {
        return kppinRiyuKbn07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_07
     *
     * @param kppinRiyuKbn07 the value for WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_07
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setKppinRiyuKbn07(String kppinRiyuKbn07) {
        this.kppinRiyuKbn07 = kppinRiyuKbn07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_08
     *
     * @return the value of WEBMDTEST.S048FRIH.MESAI_NO_08
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public Short getMesaiNo08() {
        return mesaiNo08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_08
     *
     * @param mesaiNo08 the value for WEBMDTEST.S048FRIH.MESAI_NO_08
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setMesaiNo08(Short mesaiNo08) {
        this.mesaiNo08 = mesaiNo08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_08
     *
     * @return the value of WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_08
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getKppinRiyuKbn08() {
        return kppinRiyuKbn08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_08
     *
     * @param kppinRiyuKbn08 the value for WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_08
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setKppinRiyuKbn08(String kppinRiyuKbn08) {
        this.kppinRiyuKbn08 = kppinRiyuKbn08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_09
     *
     * @return the value of WEBMDTEST.S048FRIH.MESAI_NO_09
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public Short getMesaiNo09() {
        return mesaiNo09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_09
     *
     * @param mesaiNo09 the value for WEBMDTEST.S048FRIH.MESAI_NO_09
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setMesaiNo09(Short mesaiNo09) {
        this.mesaiNo09 = mesaiNo09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_09
     *
     * @return the value of WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_09
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getKppinRiyuKbn09() {
        return kppinRiyuKbn09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_09
     *
     * @param kppinRiyuKbn09 the value for WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_09
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setKppinRiyuKbn09(String kppinRiyuKbn09) {
        this.kppinRiyuKbn09 = kppinRiyuKbn09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_10
     *
     * @return the value of WEBMDTEST.S048FRIH.MESAI_NO_10
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public Short getMesaiNo10() {
        return mesaiNo10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.MESAI_NO_10
     *
     * @param mesaiNo10 the value for WEBMDTEST.S048FRIH.MESAI_NO_10
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setMesaiNo10(Short mesaiNo10) {
        this.mesaiNo10 = mesaiNo10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_10
     *
     * @return the value of WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_10
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getKppinRiyuKbn10() {
        return kppinRiyuKbn10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_10
     *
     * @param kppinRiyuKbn10 the value for WEBMDTEST.S048FRIH.KPPIN_RIYU_KBN_10
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setKppinRiyuKbn10(String kppinRiyuKbn10) {
        this.kppinRiyuKbn10 = kppinRiyuKbn10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.CMN_TANTO_CD
     *
     * @return the value of WEBMDTEST.S048FRIH.CMN_TANTO_CD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getCmnTantoCd() {
        return cmnTantoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.CMN_TANTO_CD
     *
     * @param cmnTantoCd the value for WEBMDTEST.S048FRIH.CMN_TANTO_CD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setCmnTantoCd(String cmnTantoCd) {
        this.cmnTantoCd = cmnTantoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.CMN_TERM_ID
     *
     * @return the value of WEBMDTEST.S048FRIH.CMN_TERM_ID
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getCmnTermId() {
        return cmnTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.CMN_TERM_ID
     *
     * @param cmnTermId the value for WEBMDTEST.S048FRIH.CMN_TERM_ID
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setCmnTermId(String cmnTermId) {
        this.cmnTermId = cmnTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.CMN_INSDD
     *
     * @return the value of WEBMDTEST.S048FRIH.CMN_INSDD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getCmnInsdd() {
        return cmnInsdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.CMN_INSDD
     *
     * @param cmnInsdd the value for WEBMDTEST.S048FRIH.CMN_INSDD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setCmnInsdd(String cmnInsdd) {
        this.cmnInsdd = cmnInsdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.CMN_UPDDD
     *
     * @return the value of WEBMDTEST.S048FRIH.CMN_UPDDD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getCmnUpddd() {
        return cmnUpddd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.CMN_UPDDD
     *
     * @param cmnUpddd the value for WEBMDTEST.S048FRIH.CMN_UPDDD
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setCmnUpddd(String cmnUpddd) {
        this.cmnUpddd = cmnUpddd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMDTEST.S048FRIH.CMN_UPDTIME
     *
     * @return the value of WEBMDTEST.S048FRIH.CMN_UPDTIME
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public String getCmnUpdtime() {
        return cmnUpdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMDTEST.S048FRIH.CMN_UPDTIME
     *
     * @param cmnUpdtime the value for WEBMDTEST.S048FRIH.CMN_UPDTIME
     *
     * @mbggenerated Tue Dec 02 15:37:34 ICT 2014
     */
    public void setCmnUpdtime(String cmnUpdtime) {
        this.cmnUpdtime = cmnUpdtime;
    }
}