package jp.co.necsoft.web_md.core.common.mybatis.dto;

import java.util.ArrayList;
import java.util.List;

public class S704itstExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public S704itstExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTenCdIsNull() {
            addCriterion("TEN_CD is null");
            return (Criteria) this;
        }

        public Criteria andTenCdIsNotNull() {
            addCriterion("TEN_CD is not null");
            return (Criteria) this;
        }

        public Criteria andTenCdEqualTo(String value) {
            addCriterion("TEN_CD =", value, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdNotEqualTo(String value) {
            addCriterion("TEN_CD <>", value, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdGreaterThan(String value) {
            addCriterion("TEN_CD >", value, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdGreaterThanOrEqualTo(String value) {
            addCriterion("TEN_CD >=", value, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdLessThan(String value) {
            addCriterion("TEN_CD <", value, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdLessThanOrEqualTo(String value) {
            addCriterion("TEN_CD <=", value, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdLike(String value) {
            addCriterion("TEN_CD like", value, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdNotLike(String value) {
            addCriterion("TEN_CD not like", value, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdIn(List<String> values) {
            addCriterion("TEN_CD in", values, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdNotIn(List<String> values) {
            addCriterion("TEN_CD not in", values, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdBetween(String value1, String value2) {
            addCriterion("TEN_CD between", value1, value2, "tenCd");
            return (Criteria) this;
        }

        public Criteria andTenCdNotBetween(String value1, String value2) {
            addCriterion("TEN_CD not between", value1, value2, "tenCd");
            return (Criteria) this;
        }

        public Criteria andShnCdIsNull() {
            addCriterion("SHN_CD is null");
            return (Criteria) this;
        }

        public Criteria andShnCdIsNotNull() {
            addCriterion("SHN_CD is not null");
            return (Criteria) this;
        }

        public Criteria andShnCdEqualTo(String value) {
            addCriterion("SHN_CD =", value, "shnCd");
            return (Criteria) this;
        }

        public Criteria andShnCdNotEqualTo(String value) {
            addCriterion("SHN_CD <>", value, "shnCd");
            return (Criteria) this;
        }

        public Criteria andShnCdGreaterThan(String value) {
            addCriterion("SHN_CD >", value, "shnCd");
            return (Criteria) this;
        }

        public Criteria andShnCdGreaterThanOrEqualTo(String value) {
            addCriterion("SHN_CD >=", value, "shnCd");
            return (Criteria) this;
        }

        public Criteria andShnCdLessThan(String value) {
            addCriterion("SHN_CD <", value, "shnCd");
            return (Criteria) this;
        }

        public Criteria andShnCdLessThanOrEqualTo(String value) {
            addCriterion("SHN_CD <=", value, "shnCd");
            return (Criteria) this;
        }

        public Criteria andShnCdLike(String value) {
            addCriterion("SHN_CD like", value, "shnCd");
            return (Criteria) this;
        }

        public Criteria andShnCdNotLike(String value) {
            addCriterion("SHN_CD not like", value, "shnCd");
            return (Criteria) this;
        }

        public Criteria andShnCdIn(List<String> values) {
            addCriterion("SHN_CD in", values, "shnCd");
            return (Criteria) this;
        }

        public Criteria andShnCdNotIn(List<String> values) {
            addCriterion("SHN_CD not in", values, "shnCd");
            return (Criteria) this;
        }

        public Criteria andShnCdBetween(String value1, String value2) {
            addCriterion("SHN_CD between", value1, value2, "shnCd");
            return (Criteria) this;
        }

        public Criteria andShnCdNotBetween(String value1, String value2) {
            addCriterion("SHN_CD not between", value1, value2, "shnCd");
            return (Criteria) this;
        }

        public Criteria andSsSuIsNull() {
            addCriterion("SS_SU is null");
            return (Criteria) this;
        }

        public Criteria andSsSuIsNotNull() {
            addCriterion("SS_SU is not null");
            return (Criteria) this;
        }

        public Criteria andSsSuEqualTo(Short value) {
            addCriterion("SS_SU =", value, "ssSu");
            return (Criteria) this;
        }

        public Criteria andSsSuNotEqualTo(Short value) {
            addCriterion("SS_SU <>", value, "ssSu");
            return (Criteria) this;
        }

        public Criteria andSsSuGreaterThan(Short value) {
            addCriterion("SS_SU >", value, "ssSu");
            return (Criteria) this;
        }

        public Criteria andSsSuGreaterThanOrEqualTo(Short value) {
            addCriterion("SS_SU >=", value, "ssSu");
            return (Criteria) this;
        }

        public Criteria andSsSuLessThan(Short value) {
            addCriterion("SS_SU <", value, "ssSu");
            return (Criteria) this;
        }

        public Criteria andSsSuLessThanOrEqualTo(Short value) {
            addCriterion("SS_SU <=", value, "ssSu");
            return (Criteria) this;
        }

        public Criteria andSsSuIn(List<Short> values) {
            addCriterion("SS_SU in", values, "ssSu");
            return (Criteria) this;
        }

        public Criteria andSsSuNotIn(List<Short> values) {
            addCriterion("SS_SU not in", values, "ssSu");
            return (Criteria) this;
        }

        public Criteria andSsSuBetween(Short value1, Short value2) {
            addCriterion("SS_SU between", value1, value2, "ssSu");
            return (Criteria) this;
        }

        public Criteria andSsSuNotBetween(Short value1, Short value2) {
            addCriterion("SS_SU not between", value1, value2, "ssSu");
            return (Criteria) this;
        }

        public Criteria andSsDateIsNull() {
            addCriterion("SS_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSsDateIsNotNull() {
            addCriterion("SS_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSsDateEqualTo(String value) {
            addCriterion("SS_DATE =", value, "ssDate");
            return (Criteria) this;
        }

        public Criteria andSsDateNotEqualTo(String value) {
            addCriterion("SS_DATE <>", value, "ssDate");
            return (Criteria) this;
        }

        public Criteria andSsDateGreaterThan(String value) {
            addCriterion("SS_DATE >", value, "ssDate");
            return (Criteria) this;
        }

        public Criteria andSsDateGreaterThanOrEqualTo(String value) {
            addCriterion("SS_DATE >=", value, "ssDate");
            return (Criteria) this;
        }

        public Criteria andSsDateLessThan(String value) {
            addCriterion("SS_DATE <", value, "ssDate");
            return (Criteria) this;
        }

        public Criteria andSsDateLessThanOrEqualTo(String value) {
            addCriterion("SS_DATE <=", value, "ssDate");
            return (Criteria) this;
        }

        public Criteria andSsDateLike(String value) {
            addCriterion("SS_DATE like", value, "ssDate");
            return (Criteria) this;
        }

        public Criteria andSsDateNotLike(String value) {
            addCriterion("SS_DATE not like", value, "ssDate");
            return (Criteria) this;
        }

        public Criteria andSsDateIn(List<String> values) {
            addCriterion("SS_DATE in", values, "ssDate");
            return (Criteria) this;
        }

        public Criteria andSsDateNotIn(List<String> values) {
            addCriterion("SS_DATE not in", values, "ssDate");
            return (Criteria) this;
        }

        public Criteria andSsDateBetween(String value1, String value2) {
            addCriterion("SS_DATE between", value1, value2, "ssDate");
            return (Criteria) this;
        }

        public Criteria andSsDateNotBetween(String value1, String value2) {
            addCriterion("SS_DATE not between", value1, value2, "ssDate");
            return (Criteria) this;
        }

        public Criteria andTantoCdIsNull() {
            addCriterion("TANTO_CD is null");
            return (Criteria) this;
        }

        public Criteria andTantoCdIsNotNull() {
            addCriterion("TANTO_CD is not null");
            return (Criteria) this;
        }

        public Criteria andTantoCdEqualTo(String value) {
            addCriterion("TANTO_CD =", value, "tantoCd");
            return (Criteria) this;
        }

        public Criteria andTantoCdNotEqualTo(String value) {
            addCriterion("TANTO_CD <>", value, "tantoCd");
            return (Criteria) this;
        }

        public Criteria andTantoCdGreaterThan(String value) {
            addCriterion("TANTO_CD >", value, "tantoCd");
            return (Criteria) this;
        }

        public Criteria andTantoCdGreaterThanOrEqualTo(String value) {
            addCriterion("TANTO_CD >=", value, "tantoCd");
            return (Criteria) this;
        }

        public Criteria andTantoCdLessThan(String value) {
            addCriterion("TANTO_CD <", value, "tantoCd");
            return (Criteria) this;
        }

        public Criteria andTantoCdLessThanOrEqualTo(String value) {
            addCriterion("TANTO_CD <=", value, "tantoCd");
            return (Criteria) this;
        }

        public Criteria andTantoCdLike(String value) {
            addCriterion("TANTO_CD like", value, "tantoCd");
            return (Criteria) this;
        }

        public Criteria andTantoCdNotLike(String value) {
            addCriterion("TANTO_CD not like", value, "tantoCd");
            return (Criteria) this;
        }

        public Criteria andTantoCdIn(List<String> values) {
            addCriterion("TANTO_CD in", values, "tantoCd");
            return (Criteria) this;
        }

        public Criteria andTantoCdNotIn(List<String> values) {
            addCriterion("TANTO_CD not in", values, "tantoCd");
            return (Criteria) this;
        }

        public Criteria andTantoCdBetween(String value1, String value2) {
            addCriterion("TANTO_CD between", value1, value2, "tantoCd");
            return (Criteria) this;
        }

        public Criteria andTantoCdNotBetween(String value1, String value2) {
            addCriterion("TANTO_CD not between", value1, value2, "tantoCd");
            return (Criteria) this;
        }

        public Criteria andTermIdIsNull() {
            addCriterion("TERM_ID is null");
            return (Criteria) this;
        }

        public Criteria andTermIdIsNotNull() {
            addCriterion("TERM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTermIdEqualTo(String value) {
            addCriterion("TERM_ID =", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdNotEqualTo(String value) {
            addCriterion("TERM_ID <>", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdGreaterThan(String value) {
            addCriterion("TERM_ID >", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdGreaterThanOrEqualTo(String value) {
            addCriterion("TERM_ID >=", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdLessThan(String value) {
            addCriterion("TERM_ID <", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdLessThanOrEqualTo(String value) {
            addCriterion("TERM_ID <=", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdLike(String value) {
            addCriterion("TERM_ID like", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdNotLike(String value) {
            addCriterion("TERM_ID not like", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdIn(List<String> values) {
            addCriterion("TERM_ID in", values, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdNotIn(List<String> values) {
            addCriterion("TERM_ID not in", values, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdBetween(String value1, String value2) {
            addCriterion("TERM_ID between", value1, value2, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdNotBetween(String value1, String value2) {
            addCriterion("TERM_ID not between", value1, value2, "termId");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdIsNull() {
            addCriterion("CMN_TANTO_CD is null");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdIsNotNull() {
            addCriterion("CMN_TANTO_CD is not null");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdEqualTo(String value) {
            addCriterion("CMN_TANTO_CD =", value, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdNotEqualTo(String value) {
            addCriterion("CMN_TANTO_CD <>", value, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdGreaterThan(String value) {
            addCriterion("CMN_TANTO_CD >", value, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdGreaterThanOrEqualTo(String value) {
            addCriterion("CMN_TANTO_CD >=", value, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdLessThan(String value) {
            addCriterion("CMN_TANTO_CD <", value, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdLessThanOrEqualTo(String value) {
            addCriterion("CMN_TANTO_CD <=", value, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdLike(String value) {
            addCriterion("CMN_TANTO_CD like", value, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdNotLike(String value) {
            addCriterion("CMN_TANTO_CD not like", value, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdIn(List<String> values) {
            addCriterion("CMN_TANTO_CD in", values, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdNotIn(List<String> values) {
            addCriterion("CMN_TANTO_CD not in", values, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdBetween(String value1, String value2) {
            addCriterion("CMN_TANTO_CD between", value1, value2, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTantoCdNotBetween(String value1, String value2) {
            addCriterion("CMN_TANTO_CD not between", value1, value2, "cmnTantoCd");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdIsNull() {
            addCriterion("CMN_TERM_ID is null");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdIsNotNull() {
            addCriterion("CMN_TERM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdEqualTo(String value) {
            addCriterion("CMN_TERM_ID =", value, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdNotEqualTo(String value) {
            addCriterion("CMN_TERM_ID <>", value, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdGreaterThan(String value) {
            addCriterion("CMN_TERM_ID >", value, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdGreaterThanOrEqualTo(String value) {
            addCriterion("CMN_TERM_ID >=", value, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdLessThan(String value) {
            addCriterion("CMN_TERM_ID <", value, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdLessThanOrEqualTo(String value) {
            addCriterion("CMN_TERM_ID <=", value, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdLike(String value) {
            addCriterion("CMN_TERM_ID like", value, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdNotLike(String value) {
            addCriterion("CMN_TERM_ID not like", value, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdIn(List<String> values) {
            addCriterion("CMN_TERM_ID in", values, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdNotIn(List<String> values) {
            addCriterion("CMN_TERM_ID not in", values, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdBetween(String value1, String value2) {
            addCriterion("CMN_TERM_ID between", value1, value2, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnTermIdNotBetween(String value1, String value2) {
            addCriterion("CMN_TERM_ID not between", value1, value2, "cmnTermId");
            return (Criteria) this;
        }

        public Criteria andCmnInsddIsNull() {
            addCriterion("CMN_INSDD is null");
            return (Criteria) this;
        }

        public Criteria andCmnInsddIsNotNull() {
            addCriterion("CMN_INSDD is not null");
            return (Criteria) this;
        }

        public Criteria andCmnInsddEqualTo(String value) {
            addCriterion("CMN_INSDD =", value, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddNotEqualTo(String value) {
            addCriterion("CMN_INSDD <>", value, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddGreaterThan(String value) {
            addCriterion("CMN_INSDD >", value, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddGreaterThanOrEqualTo(String value) {
            addCriterion("CMN_INSDD >=", value, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddLessThan(String value) {
            addCriterion("CMN_INSDD <", value, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddLessThanOrEqualTo(String value) {
            addCriterion("CMN_INSDD <=", value, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddLike(String value) {
            addCriterion("CMN_INSDD like", value, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddNotLike(String value) {
            addCriterion("CMN_INSDD not like", value, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddIn(List<String> values) {
            addCriterion("CMN_INSDD in", values, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddNotIn(List<String> values) {
            addCriterion("CMN_INSDD not in", values, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddBetween(String value1, String value2) {
            addCriterion("CMN_INSDD between", value1, value2, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnInsddNotBetween(String value1, String value2) {
            addCriterion("CMN_INSDD not between", value1, value2, "cmnInsdd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddIsNull() {
            addCriterion("CMN_UPDDD is null");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddIsNotNull() {
            addCriterion("CMN_UPDDD is not null");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddEqualTo(String value) {
            addCriterion("CMN_UPDDD =", value, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddNotEqualTo(String value) {
            addCriterion("CMN_UPDDD <>", value, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddGreaterThan(String value) {
            addCriterion("CMN_UPDDD >", value, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddGreaterThanOrEqualTo(String value) {
            addCriterion("CMN_UPDDD >=", value, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddLessThan(String value) {
            addCriterion("CMN_UPDDD <", value, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddLessThanOrEqualTo(String value) {
            addCriterion("CMN_UPDDD <=", value, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddLike(String value) {
            addCriterion("CMN_UPDDD like", value, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddNotLike(String value) {
            addCriterion("CMN_UPDDD not like", value, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddIn(List<String> values) {
            addCriterion("CMN_UPDDD in", values, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddNotIn(List<String> values) {
            addCriterion("CMN_UPDDD not in", values, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddBetween(String value1, String value2) {
            addCriterion("CMN_UPDDD between", value1, value2, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdddNotBetween(String value1, String value2) {
            addCriterion("CMN_UPDDD not between", value1, value2, "cmnUpddd");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeIsNull() {
            addCriterion("CMN_UPDTIME is null");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeIsNotNull() {
            addCriterion("CMN_UPDTIME is not null");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeEqualTo(String value) {
            addCriterion("CMN_UPDTIME =", value, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeNotEqualTo(String value) {
            addCriterion("CMN_UPDTIME <>", value, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeGreaterThan(String value) {
            addCriterion("CMN_UPDTIME >", value, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeGreaterThanOrEqualTo(String value) {
            addCriterion("CMN_UPDTIME >=", value, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeLessThan(String value) {
            addCriterion("CMN_UPDTIME <", value, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeLessThanOrEqualTo(String value) {
            addCriterion("CMN_UPDTIME <=", value, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeLike(String value) {
            addCriterion("CMN_UPDTIME like", value, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeNotLike(String value) {
            addCriterion("CMN_UPDTIME not like", value, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeIn(List<String> values) {
            addCriterion("CMN_UPDTIME in", values, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeNotIn(List<String> values) {
            addCriterion("CMN_UPDTIME not in", values, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeBetween(String value1, String value2) {
            addCriterion("CMN_UPDTIME between", value1, value2, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnUpdtimeNotBetween(String value1, String value2) {
            addCriterion("CMN_UPDTIME not between", value1, value2, "cmnUpdtime");
            return (Criteria) this;
        }

        public Criteria andCmnProgramIdIsNull() {
            addCriterion("CMN_PROGRAM_ID is null");
            return (Criteria) this;
        }

        public Criteria andCmnProgramIdIsNotNull() {
            addCriterion("CMN_PROGRAM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCmnProgramIdEqualTo(String value) {
            addCriterion("CMN_PROGRAM_ID =", value, "cmnProgramId");
            return (Criteria) this;
        }

        public Criteria andCmnProgramIdNotEqualTo(String value) {
            addCriterion("CMN_PROGRAM_ID <>", value, "cmnProgramId");
            return (Criteria) this;
        }

        public Criteria andCmnProgramIdGreaterThan(String value) {
            addCriterion("CMN_PROGRAM_ID >", value, "cmnProgramId");
            return (Criteria) this;
        }

        public Criteria andCmnProgramIdGreaterThanOrEqualTo(String value) {
            addCriterion("CMN_PROGRAM_ID >=", value, "cmnProgramId");
            return (Criteria) this;
        }

        public Criteria andCmnProgramIdLessThan(String value) {
            addCriterion("CMN_PROGRAM_ID <", value, "cmnProgramId");
            return (Criteria) this;
        }

        public Criteria andCmnProgramIdLessThanOrEqualTo(String value) {
            addCriterion("CMN_PROGRAM_ID <=", value, "cmnProgramId");
            return (Criteria) this;
        }

        public Criteria andCmnProgramIdLike(String value) {
            addCriterion("CMN_PROGRAM_ID like", value, "cmnProgramId");
            return (Criteria) this;
        }

        public Criteria andCmnProgramIdNotLike(String value) {
            addCriterion("CMN_PROGRAM_ID not like", value, "cmnProgramId");
            return (Criteria) this;
        }

        public Criteria andCmnProgramIdIn(List<String> values) {
            addCriterion("CMN_PROGRAM_ID in", values, "cmnProgramId");
            return (Criteria) this;
        }

        public Criteria andCmnProgramIdNotIn(List<String> values) {
            addCriterion("CMN_PROGRAM_ID not in", values, "cmnProgramId");
            return (Criteria) this;
        }

        public Criteria andCmnProgramIdBetween(String value1, String value2) {
            addCriterion("CMN_PROGRAM_ID between", value1, value2, "cmnProgramId");
            return (Criteria) this;
        }

        public Criteria andCmnProgramIdNotBetween(String value1, String value2) {
            addCriterion("CMN_PROGRAM_ID not between", value1, value2, "cmnProgramId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 08 13:53:14 ICT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WEBMD.S704ITST
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}