package jp.co.necsoft.web_md.core.common.mybatis.dto;

public class S704itst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S704ITST.TEN_CD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    private String tenCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S704ITST.SHN_CD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    private String shnCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S704ITST.SS_SU
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    private Short ssSu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S704ITST.SS_DATE
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    private String ssDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S704ITST.TANTO_CD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    private String tantoCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S704ITST.TERM_ID
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    private String termId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S704ITST.CMN_TANTO_CD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    private String cmnTantoCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S704ITST.CMN_TERM_ID
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    private String cmnTermId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S704ITST.CMN_INSDD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    private String cmnInsdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S704ITST.CMN_UPDDD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    private String cmnUpddd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S704ITST.CMN_UPDTIME
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    private String cmnUpdtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.S704ITST.CMN_PROGRAM_ID
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    private String cmnProgramId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S704ITST.TEN_CD
     *
     * @return the value of WEBMD.S704ITST.TEN_CD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public String getTenCd() {
        return tenCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S704ITST.TEN_CD
     *
     * @param tenCd the value for WEBMD.S704ITST.TEN_CD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public void setTenCd(String tenCd) {
        this.tenCd = tenCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S704ITST.SHN_CD
     *
     * @return the value of WEBMD.S704ITST.SHN_CD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public String getShnCd() {
        return shnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S704ITST.SHN_CD
     *
     * @param shnCd the value for WEBMD.S704ITST.SHN_CD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public void setShnCd(String shnCd) {
        this.shnCd = shnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S704ITST.SS_SU
     *
     * @return the value of WEBMD.S704ITST.SS_SU
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public Short getSsSu() {
        return ssSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S704ITST.SS_SU
     *
     * @param ssSu the value for WEBMD.S704ITST.SS_SU
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public void setSsSu(Short ssSu) {
        this.ssSu = ssSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S704ITST.SS_DATE
     *
     * @return the value of WEBMD.S704ITST.SS_DATE
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public String getSsDate() {
        return ssDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S704ITST.SS_DATE
     *
     * @param ssDate the value for WEBMD.S704ITST.SS_DATE
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public void setSsDate(String ssDate) {
        this.ssDate = ssDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S704ITST.TANTO_CD
     *
     * @return the value of WEBMD.S704ITST.TANTO_CD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public String getTantoCd() {
        return tantoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S704ITST.TANTO_CD
     *
     * @param tantoCd the value for WEBMD.S704ITST.TANTO_CD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public void setTantoCd(String tantoCd) {
        this.tantoCd = tantoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S704ITST.TERM_ID
     *
     * @return the value of WEBMD.S704ITST.TERM_ID
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public String getTermId() {
        return termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S704ITST.TERM_ID
     *
     * @param termId the value for WEBMD.S704ITST.TERM_ID
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public void setTermId(String termId) {
        this.termId = termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S704ITST.CMN_TANTO_CD
     *
     * @return the value of WEBMD.S704ITST.CMN_TANTO_CD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public String getCmnTantoCd() {
        return cmnTantoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S704ITST.CMN_TANTO_CD
     *
     * @param cmnTantoCd the value for WEBMD.S704ITST.CMN_TANTO_CD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public void setCmnTantoCd(String cmnTantoCd) {
        this.cmnTantoCd = cmnTantoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S704ITST.CMN_TERM_ID
     *
     * @return the value of WEBMD.S704ITST.CMN_TERM_ID
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public String getCmnTermId() {
        return cmnTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S704ITST.CMN_TERM_ID
     *
     * @param cmnTermId the value for WEBMD.S704ITST.CMN_TERM_ID
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public void setCmnTermId(String cmnTermId) {
        this.cmnTermId = cmnTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S704ITST.CMN_INSDD
     *
     * @return the value of WEBMD.S704ITST.CMN_INSDD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public String getCmnInsdd() {
        return cmnInsdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S704ITST.CMN_INSDD
     *
     * @param cmnInsdd the value for WEBMD.S704ITST.CMN_INSDD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public void setCmnInsdd(String cmnInsdd) {
        this.cmnInsdd = cmnInsdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S704ITST.CMN_UPDDD
     *
     * @return the value of WEBMD.S704ITST.CMN_UPDDD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public String getCmnUpddd() {
        return cmnUpddd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S704ITST.CMN_UPDDD
     *
     * @param cmnUpddd the value for WEBMD.S704ITST.CMN_UPDDD
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public void setCmnUpddd(String cmnUpddd) {
        this.cmnUpddd = cmnUpddd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S704ITST.CMN_UPDTIME
     *
     * @return the value of WEBMD.S704ITST.CMN_UPDTIME
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public String getCmnUpdtime() {
        return cmnUpdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S704ITST.CMN_UPDTIME
     *
     * @param cmnUpdtime the value for WEBMD.S704ITST.CMN_UPDTIME
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public void setCmnUpdtime(String cmnUpdtime) {
        this.cmnUpdtime = cmnUpdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.S704ITST.CMN_PROGRAM_ID
     *
     * @return the value of WEBMD.S704ITST.CMN_PROGRAM_ID
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public String getCmnProgramId() {
        return cmnProgramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.S704ITST.CMN_PROGRAM_ID
     *
     * @param cmnProgramId the value for WEBMD.S704ITST.CMN_PROGRAM_ID
     *
     * @mbggenerated Mon Jun 08 13:53:14 ICT 2015
     */
    public void setCmnProgramId(String cmnProgramId) {
        this.cmnProgramId = cmnProgramId;
    }
}