package jp.co.necsoft.web_md.core.common.mybatis.dto;

import java.math.BigDecimal;

public class Se02tnot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.JAN_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String janCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.TNA_UNY_DD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String tnaUnyDd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.TEN_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String tenCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.URB_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String urbCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.GONDORA
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String gondora;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.DAN
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private Short dan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.KAISYA_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String kaisyaCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.JIGYOUBU_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String jigyoubuCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.BMN_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String bmnCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.CHU_BNR_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String chuBnrCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.TNP_GNK_KBN
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String tnpGnkKbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.GENK
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private BigDecimal genk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.BAIK
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private Integer baik;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.ZIK_SU
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private BigDecimal zikSu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.BAT_FLG
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String batFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.TAB_ID
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String tabId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.TAB_DD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String tabDd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.TAB_TIME
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String tabTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.INS_TAB_DD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String insTabDd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.INS_TAB_TIME
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String insTabTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.CMN_TANTO_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String cmnTantoCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.CMN_TERM_ID
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String cmnTermId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.CMN_INSDD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String cmnInsdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.CMN_INSTIME
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String cmnInstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.CMN_UPDDD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String cmnUpddd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.SE02TNOT.CMN_UPDTIME
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    private String cmnUpdtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.JAN_CD
     *
     * @return the value of WEBMD.SE02TNOT.JAN_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getJanCd() {
        return janCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.JAN_CD
     *
     * @param janCd the value for WEBMD.SE02TNOT.JAN_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setJanCd(String janCd) {
        this.janCd = janCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.TNA_UNY_DD
     *
     * @return the value of WEBMD.SE02TNOT.TNA_UNY_DD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getTnaUnyDd() {
        return tnaUnyDd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.TNA_UNY_DD
     *
     * @param tnaUnyDd the value for WEBMD.SE02TNOT.TNA_UNY_DD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setTnaUnyDd(String tnaUnyDd) {
        this.tnaUnyDd = tnaUnyDd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.TEN_CD
     *
     * @return the value of WEBMD.SE02TNOT.TEN_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getTenCd() {
        return tenCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.TEN_CD
     *
     * @param tenCd the value for WEBMD.SE02TNOT.TEN_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setTenCd(String tenCd) {
        this.tenCd = tenCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.URB_CD
     *
     * @return the value of WEBMD.SE02TNOT.URB_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getUrbCd() {
        return urbCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.URB_CD
     *
     * @param urbCd the value for WEBMD.SE02TNOT.URB_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setUrbCd(String urbCd) {
        this.urbCd = urbCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.GONDORA
     *
     * @return the value of WEBMD.SE02TNOT.GONDORA
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getGondora() {
        return gondora;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.GONDORA
     *
     * @param gondora the value for WEBMD.SE02TNOT.GONDORA
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setGondora(String gondora) {
        this.gondora = gondora;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.DAN
     *
     * @return the value of WEBMD.SE02TNOT.DAN
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public Short getDan() {
        return dan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.DAN
     *
     * @param dan the value for WEBMD.SE02TNOT.DAN
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setDan(Short dan) {
        this.dan = dan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.KAISYA_CD
     *
     * @return the value of WEBMD.SE02TNOT.KAISYA_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getKaisyaCd() {
        return kaisyaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.KAISYA_CD
     *
     * @param kaisyaCd the value for WEBMD.SE02TNOT.KAISYA_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setKaisyaCd(String kaisyaCd) {
        this.kaisyaCd = kaisyaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.JIGYOUBU_CD
     *
     * @return the value of WEBMD.SE02TNOT.JIGYOUBU_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getJigyoubuCd() {
        return jigyoubuCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.JIGYOUBU_CD
     *
     * @param jigyoubuCd the value for WEBMD.SE02TNOT.JIGYOUBU_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setJigyoubuCd(String jigyoubuCd) {
        this.jigyoubuCd = jigyoubuCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.BMN_CD
     *
     * @return the value of WEBMD.SE02TNOT.BMN_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getBmnCd() {
        return bmnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.BMN_CD
     *
     * @param bmnCd the value for WEBMD.SE02TNOT.BMN_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setBmnCd(String bmnCd) {
        this.bmnCd = bmnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.CHU_BNR_CD
     *
     * @return the value of WEBMD.SE02TNOT.CHU_BNR_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getChuBnrCd() {
        return chuBnrCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.CHU_BNR_CD
     *
     * @param chuBnrCd the value for WEBMD.SE02TNOT.CHU_BNR_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setChuBnrCd(String chuBnrCd) {
        this.chuBnrCd = chuBnrCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.TNP_GNK_KBN
     *
     * @return the value of WEBMD.SE02TNOT.TNP_GNK_KBN
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getTnpGnkKbn() {
        return tnpGnkKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.TNP_GNK_KBN
     *
     * @param tnpGnkKbn the value for WEBMD.SE02TNOT.TNP_GNK_KBN
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setTnpGnkKbn(String tnpGnkKbn) {
        this.tnpGnkKbn = tnpGnkKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.GENK
     *
     * @return the value of WEBMD.SE02TNOT.GENK
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public BigDecimal getGenk() {
        return genk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.GENK
     *
     * @param genk the value for WEBMD.SE02TNOT.GENK
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setGenk(BigDecimal genk) {
        this.genk = genk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.BAIK
     *
     * @return the value of WEBMD.SE02TNOT.BAIK
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public Integer getBaik() {
        return baik;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.BAIK
     *
     * @param baik the value for WEBMD.SE02TNOT.BAIK
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setBaik(Integer baik) {
        this.baik = baik;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.ZIK_SU
     *
     * @return the value of WEBMD.SE02TNOT.ZIK_SU
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public BigDecimal getZikSu() {
        return zikSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.ZIK_SU
     *
     * @param zikSu the value for WEBMD.SE02TNOT.ZIK_SU
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setZikSu(BigDecimal zikSu) {
        this.zikSu = zikSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.BAT_FLG
     *
     * @return the value of WEBMD.SE02TNOT.BAT_FLG
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getBatFlg() {
        return batFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.BAT_FLG
     *
     * @param batFlg the value for WEBMD.SE02TNOT.BAT_FLG
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setBatFlg(String batFlg) {
        this.batFlg = batFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.TAB_ID
     *
     * @return the value of WEBMD.SE02TNOT.TAB_ID
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getTabId() {
        return tabId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.TAB_ID
     *
     * @param tabId the value for WEBMD.SE02TNOT.TAB_ID
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setTabId(String tabId) {
        this.tabId = tabId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.TAB_DD
     *
     * @return the value of WEBMD.SE02TNOT.TAB_DD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getTabDd() {
        return tabDd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.TAB_DD
     *
     * @param tabDd the value for WEBMD.SE02TNOT.TAB_DD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setTabDd(String tabDd) {
        this.tabDd = tabDd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.TAB_TIME
     *
     * @return the value of WEBMD.SE02TNOT.TAB_TIME
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getTabTime() {
        return tabTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.TAB_TIME
     *
     * @param tabTime the value for WEBMD.SE02TNOT.TAB_TIME
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setTabTime(String tabTime) {
        this.tabTime = tabTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.INS_TAB_DD
     *
     * @return the value of WEBMD.SE02TNOT.INS_TAB_DD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getInsTabDd() {
        return insTabDd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.INS_TAB_DD
     *
     * @param insTabDd the value for WEBMD.SE02TNOT.INS_TAB_DD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setInsTabDd(String insTabDd) {
        this.insTabDd = insTabDd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.INS_TAB_TIME
     *
     * @return the value of WEBMD.SE02TNOT.INS_TAB_TIME
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getInsTabTime() {
        return insTabTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.INS_TAB_TIME
     *
     * @param insTabTime the value for WEBMD.SE02TNOT.INS_TAB_TIME
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setInsTabTime(String insTabTime) {
        this.insTabTime = insTabTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.CMN_TANTO_CD
     *
     * @return the value of WEBMD.SE02TNOT.CMN_TANTO_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getCmnTantoCd() {
        return cmnTantoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.CMN_TANTO_CD
     *
     * @param cmnTantoCd the value for WEBMD.SE02TNOT.CMN_TANTO_CD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setCmnTantoCd(String cmnTantoCd) {
        this.cmnTantoCd = cmnTantoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.CMN_TERM_ID
     *
     * @return the value of WEBMD.SE02TNOT.CMN_TERM_ID
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getCmnTermId() {
        return cmnTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.CMN_TERM_ID
     *
     * @param cmnTermId the value for WEBMD.SE02TNOT.CMN_TERM_ID
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setCmnTermId(String cmnTermId) {
        this.cmnTermId = cmnTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.CMN_INSDD
     *
     * @return the value of WEBMD.SE02TNOT.CMN_INSDD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getCmnInsdd() {
        return cmnInsdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.CMN_INSDD
     *
     * @param cmnInsdd the value for WEBMD.SE02TNOT.CMN_INSDD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setCmnInsdd(String cmnInsdd) {
        this.cmnInsdd = cmnInsdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.CMN_INSTIME
     *
     * @return the value of WEBMD.SE02TNOT.CMN_INSTIME
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getCmnInstime() {
        return cmnInstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.CMN_INSTIME
     *
     * @param cmnInstime the value for WEBMD.SE02TNOT.CMN_INSTIME
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setCmnInstime(String cmnInstime) {
        this.cmnInstime = cmnInstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.CMN_UPDDD
     *
     * @return the value of WEBMD.SE02TNOT.CMN_UPDDD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getCmnUpddd() {
        return cmnUpddd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.CMN_UPDDD
     *
     * @param cmnUpddd the value for WEBMD.SE02TNOT.CMN_UPDDD
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setCmnUpddd(String cmnUpddd) {
        this.cmnUpddd = cmnUpddd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.SE02TNOT.CMN_UPDTIME
     *
     * @return the value of WEBMD.SE02TNOT.CMN_UPDTIME
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public String getCmnUpdtime() {
        return cmnUpdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.SE02TNOT.CMN_UPDTIME
     *
     * @param cmnUpdtime the value for WEBMD.SE02TNOT.CMN_UPDTIME
     *
     * @mbggenerated Thu Jan 29 09:31:22 JST 2015
     */
    public void setCmnUpdtime(String cmnUpdtime) {
        this.cmnUpdtime = cmnUpdtime;
    }
}