package jp.co.necsoft.web_md.core.common.mybatis.dto;

import java.math.BigDecimal;

public class U700jkus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.JIGYOBU_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String jigyobuCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.TEN_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String tenCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.BMN_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String bmnCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.CHU_BNR_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String chuBnrCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.SHO_BNR_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String shoBnrCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.KEIJO_YMD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String keijoYmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.REJI_NO
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rejiNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.KEIJO_TIME
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private Short keijoTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.KYAKSU
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private Long kyaksu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.URI_KIN
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private Long uriKin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.KYAKSU_RUI
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private Long kyaksuRui;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.URI_KIN_RUI
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private Long uriKinRui;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.DELETE_FLG
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.CHUSHUTU_FLG01
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String chushutuFlg01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.CHUSHUTU_FLG02
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String chushutuFlg02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.CHUSHUTU_FLG03
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String chushutuFlg03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.CHUSHUTU_FLG04
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String chushutuFlg04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.CHUSHUTU_FLG05
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String chushutuFlg05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_KBN1_1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvKbn11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_KBN1_2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvKbn12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_KBN1_3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvKbn13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_KBN1_4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvKbn14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_KBN1_5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvKbn15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_KBN2_1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvKbn21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_KBN2_2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvKbn22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_KBN2_3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvKbn23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_KBN2_4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvKbn24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_KBN2_5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvKbn25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_SU1_1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private Integer rsvSu11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_SU1_2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private Integer rsvSu12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_SU1_3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private Integer rsvSu13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_SU1_4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private Integer rsvSu14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_SU1_5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private Integer rsvSu15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_SU2_1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private BigDecimal rsvSu21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_SU2_2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private BigDecimal rsvSu22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_SU2_3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private BigDecimal rsvSu23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_SU2_4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private BigDecimal rsvSu24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_SU2_5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private BigDecimal rsvSu25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_CD1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvCd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_CD2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvCd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_CD3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvCd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_CD4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvCd4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_CD5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvCd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_DD1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvDd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_DD2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvDd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_DD3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvDd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_DD4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvDd4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_DD5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvDd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_NM1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvNm1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_NM2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvNm2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_NM3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvNm3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_NM4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvNm4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.RSV_NM5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String rsvNm5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.CMN_TANTO_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String cmnTantoCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.CMN_TERM_ID
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String cmnTermId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.CMN_INSDD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String cmnInsdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.CMN_UPDDD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String cmnUpddd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.CMN_UPDTIME
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String cmnUpdtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEBMD.U700JKUS.CMN_PROGRAM_ID
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    private String cmnProgramId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.JIGYOBU_CD
     *
     * @return the value of WEBMD.U700JKUS.JIGYOBU_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getJigyobuCd() {
        return jigyobuCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.JIGYOBU_CD
     *
     * @param jigyobuCd the value for WEBMD.U700JKUS.JIGYOBU_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setJigyobuCd(String jigyobuCd) {
        this.jigyobuCd = jigyobuCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.TEN_CD
     *
     * @return the value of WEBMD.U700JKUS.TEN_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getTenCd() {
        return tenCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.TEN_CD
     *
     * @param tenCd the value for WEBMD.U700JKUS.TEN_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setTenCd(String tenCd) {
        this.tenCd = tenCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.BMN_CD
     *
     * @return the value of WEBMD.U700JKUS.BMN_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getBmnCd() {
        return bmnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.BMN_CD
     *
     * @param bmnCd the value for WEBMD.U700JKUS.BMN_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setBmnCd(String bmnCd) {
        this.bmnCd = bmnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.CHU_BNR_CD
     *
     * @return the value of WEBMD.U700JKUS.CHU_BNR_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getChuBnrCd() {
        return chuBnrCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.CHU_BNR_CD
     *
     * @param chuBnrCd the value for WEBMD.U700JKUS.CHU_BNR_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setChuBnrCd(String chuBnrCd) {
        this.chuBnrCd = chuBnrCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.SHO_BNR_CD
     *
     * @return the value of WEBMD.U700JKUS.SHO_BNR_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getShoBnrCd() {
        return shoBnrCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.SHO_BNR_CD
     *
     * @param shoBnrCd the value for WEBMD.U700JKUS.SHO_BNR_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setShoBnrCd(String shoBnrCd) {
        this.shoBnrCd = shoBnrCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.KEIJO_YMD
     *
     * @return the value of WEBMD.U700JKUS.KEIJO_YMD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getKeijoYmd() {
        return keijoYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.KEIJO_YMD
     *
     * @param keijoYmd the value for WEBMD.U700JKUS.KEIJO_YMD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setKeijoYmd(String keijoYmd) {
        this.keijoYmd = keijoYmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.REJI_NO
     *
     * @return the value of WEBMD.U700JKUS.REJI_NO
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRejiNo() {
        return rejiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.REJI_NO
     *
     * @param rejiNo the value for WEBMD.U700JKUS.REJI_NO
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRejiNo(String rejiNo) {
        this.rejiNo = rejiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.KEIJO_TIME
     *
     * @return the value of WEBMD.U700JKUS.KEIJO_TIME
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public Short getKeijoTime() {
        return keijoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.KEIJO_TIME
     *
     * @param keijoTime the value for WEBMD.U700JKUS.KEIJO_TIME
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setKeijoTime(Short keijoTime) {
        this.keijoTime = keijoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.KYAKSU
     *
     * @return the value of WEBMD.U700JKUS.KYAKSU
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public Long getKyaksu() {
        return kyaksu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.KYAKSU
     *
     * @param kyaksu the value for WEBMD.U700JKUS.KYAKSU
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setKyaksu(Long kyaksu) {
        this.kyaksu = kyaksu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.URI_KIN
     *
     * @return the value of WEBMD.U700JKUS.URI_KIN
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public Long getUriKin() {
        return uriKin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.URI_KIN
     *
     * @param uriKin the value for WEBMD.U700JKUS.URI_KIN
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setUriKin(Long uriKin) {
        this.uriKin = uriKin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.KYAKSU_RUI
     *
     * @return the value of WEBMD.U700JKUS.KYAKSU_RUI
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public Long getKyaksuRui() {
        return kyaksuRui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.KYAKSU_RUI
     *
     * @param kyaksuRui the value for WEBMD.U700JKUS.KYAKSU_RUI
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setKyaksuRui(Long kyaksuRui) {
        this.kyaksuRui = kyaksuRui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.URI_KIN_RUI
     *
     * @return the value of WEBMD.U700JKUS.URI_KIN_RUI
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public Long getUriKinRui() {
        return uriKinRui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.URI_KIN_RUI
     *
     * @param uriKinRui the value for WEBMD.U700JKUS.URI_KIN_RUI
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setUriKinRui(Long uriKinRui) {
        this.uriKinRui = uriKinRui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.DELETE_FLG
     *
     * @return the value of WEBMD.U700JKUS.DELETE_FLG
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.DELETE_FLG
     *
     * @param deleteFlg the value for WEBMD.U700JKUS.DELETE_FLG
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setDeleteFlg(String deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.CHUSHUTU_FLG01
     *
     * @return the value of WEBMD.U700JKUS.CHUSHUTU_FLG01
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getChushutuFlg01() {
        return chushutuFlg01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.CHUSHUTU_FLG01
     *
     * @param chushutuFlg01 the value for WEBMD.U700JKUS.CHUSHUTU_FLG01
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setChushutuFlg01(String chushutuFlg01) {
        this.chushutuFlg01 = chushutuFlg01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.CHUSHUTU_FLG02
     *
     * @return the value of WEBMD.U700JKUS.CHUSHUTU_FLG02
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getChushutuFlg02() {
        return chushutuFlg02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.CHUSHUTU_FLG02
     *
     * @param chushutuFlg02 the value for WEBMD.U700JKUS.CHUSHUTU_FLG02
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setChushutuFlg02(String chushutuFlg02) {
        this.chushutuFlg02 = chushutuFlg02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.CHUSHUTU_FLG03
     *
     * @return the value of WEBMD.U700JKUS.CHUSHUTU_FLG03
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getChushutuFlg03() {
        return chushutuFlg03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.CHUSHUTU_FLG03
     *
     * @param chushutuFlg03 the value for WEBMD.U700JKUS.CHUSHUTU_FLG03
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setChushutuFlg03(String chushutuFlg03) {
        this.chushutuFlg03 = chushutuFlg03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.CHUSHUTU_FLG04
     *
     * @return the value of WEBMD.U700JKUS.CHUSHUTU_FLG04
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getChushutuFlg04() {
        return chushutuFlg04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.CHUSHUTU_FLG04
     *
     * @param chushutuFlg04 the value for WEBMD.U700JKUS.CHUSHUTU_FLG04
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setChushutuFlg04(String chushutuFlg04) {
        this.chushutuFlg04 = chushutuFlg04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.CHUSHUTU_FLG05
     *
     * @return the value of WEBMD.U700JKUS.CHUSHUTU_FLG05
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getChushutuFlg05() {
        return chushutuFlg05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.CHUSHUTU_FLG05
     *
     * @param chushutuFlg05 the value for WEBMD.U700JKUS.CHUSHUTU_FLG05
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setChushutuFlg05(String chushutuFlg05) {
        this.chushutuFlg05 = chushutuFlg05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_KBN1_1
     *
     * @return the value of WEBMD.U700JKUS.RSV_KBN1_1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvKbn11() {
        return rsvKbn11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_KBN1_1
     *
     * @param rsvKbn11 the value for WEBMD.U700JKUS.RSV_KBN1_1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvKbn11(String rsvKbn11) {
        this.rsvKbn11 = rsvKbn11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_KBN1_2
     *
     * @return the value of WEBMD.U700JKUS.RSV_KBN1_2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvKbn12() {
        return rsvKbn12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_KBN1_2
     *
     * @param rsvKbn12 the value for WEBMD.U700JKUS.RSV_KBN1_2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvKbn12(String rsvKbn12) {
        this.rsvKbn12 = rsvKbn12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_KBN1_3
     *
     * @return the value of WEBMD.U700JKUS.RSV_KBN1_3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvKbn13() {
        return rsvKbn13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_KBN1_3
     *
     * @param rsvKbn13 the value for WEBMD.U700JKUS.RSV_KBN1_3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvKbn13(String rsvKbn13) {
        this.rsvKbn13 = rsvKbn13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_KBN1_4
     *
     * @return the value of WEBMD.U700JKUS.RSV_KBN1_4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvKbn14() {
        return rsvKbn14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_KBN1_4
     *
     * @param rsvKbn14 the value for WEBMD.U700JKUS.RSV_KBN1_4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvKbn14(String rsvKbn14) {
        this.rsvKbn14 = rsvKbn14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_KBN1_5
     *
     * @return the value of WEBMD.U700JKUS.RSV_KBN1_5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvKbn15() {
        return rsvKbn15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_KBN1_5
     *
     * @param rsvKbn15 the value for WEBMD.U700JKUS.RSV_KBN1_5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvKbn15(String rsvKbn15) {
        this.rsvKbn15 = rsvKbn15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_KBN2_1
     *
     * @return the value of WEBMD.U700JKUS.RSV_KBN2_1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvKbn21() {
        return rsvKbn21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_KBN2_1
     *
     * @param rsvKbn21 the value for WEBMD.U700JKUS.RSV_KBN2_1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvKbn21(String rsvKbn21) {
        this.rsvKbn21 = rsvKbn21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_KBN2_2
     *
     * @return the value of WEBMD.U700JKUS.RSV_KBN2_2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvKbn22() {
        return rsvKbn22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_KBN2_2
     *
     * @param rsvKbn22 the value for WEBMD.U700JKUS.RSV_KBN2_2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvKbn22(String rsvKbn22) {
        this.rsvKbn22 = rsvKbn22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_KBN2_3
     *
     * @return the value of WEBMD.U700JKUS.RSV_KBN2_3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvKbn23() {
        return rsvKbn23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_KBN2_3
     *
     * @param rsvKbn23 the value for WEBMD.U700JKUS.RSV_KBN2_3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvKbn23(String rsvKbn23) {
        this.rsvKbn23 = rsvKbn23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_KBN2_4
     *
     * @return the value of WEBMD.U700JKUS.RSV_KBN2_4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvKbn24() {
        return rsvKbn24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_KBN2_4
     *
     * @param rsvKbn24 the value for WEBMD.U700JKUS.RSV_KBN2_4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvKbn24(String rsvKbn24) {
        this.rsvKbn24 = rsvKbn24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_KBN2_5
     *
     * @return the value of WEBMD.U700JKUS.RSV_KBN2_5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvKbn25() {
        return rsvKbn25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_KBN2_5
     *
     * @param rsvKbn25 the value for WEBMD.U700JKUS.RSV_KBN2_5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvKbn25(String rsvKbn25) {
        this.rsvKbn25 = rsvKbn25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_SU1_1
     *
     * @return the value of WEBMD.U700JKUS.RSV_SU1_1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public Integer getRsvSu11() {
        return rsvSu11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_SU1_1
     *
     * @param rsvSu11 the value for WEBMD.U700JKUS.RSV_SU1_1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvSu11(Integer rsvSu11) {
        this.rsvSu11 = rsvSu11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_SU1_2
     *
     * @return the value of WEBMD.U700JKUS.RSV_SU1_2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public Integer getRsvSu12() {
        return rsvSu12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_SU1_2
     *
     * @param rsvSu12 the value for WEBMD.U700JKUS.RSV_SU1_2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvSu12(Integer rsvSu12) {
        this.rsvSu12 = rsvSu12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_SU1_3
     *
     * @return the value of WEBMD.U700JKUS.RSV_SU1_3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public Integer getRsvSu13() {
        return rsvSu13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_SU1_3
     *
     * @param rsvSu13 the value for WEBMD.U700JKUS.RSV_SU1_3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvSu13(Integer rsvSu13) {
        this.rsvSu13 = rsvSu13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_SU1_4
     *
     * @return the value of WEBMD.U700JKUS.RSV_SU1_4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public Integer getRsvSu14() {
        return rsvSu14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_SU1_4
     *
     * @param rsvSu14 the value for WEBMD.U700JKUS.RSV_SU1_4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvSu14(Integer rsvSu14) {
        this.rsvSu14 = rsvSu14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_SU1_5
     *
     * @return the value of WEBMD.U700JKUS.RSV_SU1_5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public Integer getRsvSu15() {
        return rsvSu15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_SU1_5
     *
     * @param rsvSu15 the value for WEBMD.U700JKUS.RSV_SU1_5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvSu15(Integer rsvSu15) {
        this.rsvSu15 = rsvSu15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_SU2_1
     *
     * @return the value of WEBMD.U700JKUS.RSV_SU2_1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public BigDecimal getRsvSu21() {
        return rsvSu21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_SU2_1
     *
     * @param rsvSu21 the value for WEBMD.U700JKUS.RSV_SU2_1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvSu21(BigDecimal rsvSu21) {
        this.rsvSu21 = rsvSu21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_SU2_2
     *
     * @return the value of WEBMD.U700JKUS.RSV_SU2_2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public BigDecimal getRsvSu22() {
        return rsvSu22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_SU2_2
     *
     * @param rsvSu22 the value for WEBMD.U700JKUS.RSV_SU2_2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvSu22(BigDecimal rsvSu22) {
        this.rsvSu22 = rsvSu22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_SU2_3
     *
     * @return the value of WEBMD.U700JKUS.RSV_SU2_3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public BigDecimal getRsvSu23() {
        return rsvSu23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_SU2_3
     *
     * @param rsvSu23 the value for WEBMD.U700JKUS.RSV_SU2_3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvSu23(BigDecimal rsvSu23) {
        this.rsvSu23 = rsvSu23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_SU2_4
     *
     * @return the value of WEBMD.U700JKUS.RSV_SU2_4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public BigDecimal getRsvSu24() {
        return rsvSu24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_SU2_4
     *
     * @param rsvSu24 the value for WEBMD.U700JKUS.RSV_SU2_4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvSu24(BigDecimal rsvSu24) {
        this.rsvSu24 = rsvSu24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_SU2_5
     *
     * @return the value of WEBMD.U700JKUS.RSV_SU2_5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public BigDecimal getRsvSu25() {
        return rsvSu25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_SU2_5
     *
     * @param rsvSu25 the value for WEBMD.U700JKUS.RSV_SU2_5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvSu25(BigDecimal rsvSu25) {
        this.rsvSu25 = rsvSu25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_CD1
     *
     * @return the value of WEBMD.U700JKUS.RSV_CD1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvCd1() {
        return rsvCd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_CD1
     *
     * @param rsvCd1 the value for WEBMD.U700JKUS.RSV_CD1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvCd1(String rsvCd1) {
        this.rsvCd1 = rsvCd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_CD2
     *
     * @return the value of WEBMD.U700JKUS.RSV_CD2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvCd2() {
        return rsvCd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_CD2
     *
     * @param rsvCd2 the value for WEBMD.U700JKUS.RSV_CD2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvCd2(String rsvCd2) {
        this.rsvCd2 = rsvCd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_CD3
     *
     * @return the value of WEBMD.U700JKUS.RSV_CD3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvCd3() {
        return rsvCd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_CD3
     *
     * @param rsvCd3 the value for WEBMD.U700JKUS.RSV_CD3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvCd3(String rsvCd3) {
        this.rsvCd3 = rsvCd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_CD4
     *
     * @return the value of WEBMD.U700JKUS.RSV_CD4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvCd4() {
        return rsvCd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_CD4
     *
     * @param rsvCd4 the value for WEBMD.U700JKUS.RSV_CD4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvCd4(String rsvCd4) {
        this.rsvCd4 = rsvCd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_CD5
     *
     * @return the value of WEBMD.U700JKUS.RSV_CD5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvCd5() {
        return rsvCd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_CD5
     *
     * @param rsvCd5 the value for WEBMD.U700JKUS.RSV_CD5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvCd5(String rsvCd5) {
        this.rsvCd5 = rsvCd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_DD1
     *
     * @return the value of WEBMD.U700JKUS.RSV_DD1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvDd1() {
        return rsvDd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_DD1
     *
     * @param rsvDd1 the value for WEBMD.U700JKUS.RSV_DD1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvDd1(String rsvDd1) {
        this.rsvDd1 = rsvDd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_DD2
     *
     * @return the value of WEBMD.U700JKUS.RSV_DD2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvDd2() {
        return rsvDd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_DD2
     *
     * @param rsvDd2 the value for WEBMD.U700JKUS.RSV_DD2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvDd2(String rsvDd2) {
        this.rsvDd2 = rsvDd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_DD3
     *
     * @return the value of WEBMD.U700JKUS.RSV_DD3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvDd3() {
        return rsvDd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_DD3
     *
     * @param rsvDd3 the value for WEBMD.U700JKUS.RSV_DD3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvDd3(String rsvDd3) {
        this.rsvDd3 = rsvDd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_DD4
     *
     * @return the value of WEBMD.U700JKUS.RSV_DD4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvDd4() {
        return rsvDd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_DD4
     *
     * @param rsvDd4 the value for WEBMD.U700JKUS.RSV_DD4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvDd4(String rsvDd4) {
        this.rsvDd4 = rsvDd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_DD5
     *
     * @return the value of WEBMD.U700JKUS.RSV_DD5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvDd5() {
        return rsvDd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_DD5
     *
     * @param rsvDd5 the value for WEBMD.U700JKUS.RSV_DD5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvDd5(String rsvDd5) {
        this.rsvDd5 = rsvDd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_NM1
     *
     * @return the value of WEBMD.U700JKUS.RSV_NM1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvNm1() {
        return rsvNm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_NM1
     *
     * @param rsvNm1 the value for WEBMD.U700JKUS.RSV_NM1
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvNm1(String rsvNm1) {
        this.rsvNm1 = rsvNm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_NM2
     *
     * @return the value of WEBMD.U700JKUS.RSV_NM2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvNm2() {
        return rsvNm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_NM2
     *
     * @param rsvNm2 the value for WEBMD.U700JKUS.RSV_NM2
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvNm2(String rsvNm2) {
        this.rsvNm2 = rsvNm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_NM3
     *
     * @return the value of WEBMD.U700JKUS.RSV_NM3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvNm3() {
        return rsvNm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_NM3
     *
     * @param rsvNm3 the value for WEBMD.U700JKUS.RSV_NM3
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvNm3(String rsvNm3) {
        this.rsvNm3 = rsvNm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_NM4
     *
     * @return the value of WEBMD.U700JKUS.RSV_NM4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvNm4() {
        return rsvNm4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_NM4
     *
     * @param rsvNm4 the value for WEBMD.U700JKUS.RSV_NM4
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvNm4(String rsvNm4) {
        this.rsvNm4 = rsvNm4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.RSV_NM5
     *
     * @return the value of WEBMD.U700JKUS.RSV_NM5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getRsvNm5() {
        return rsvNm5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.RSV_NM5
     *
     * @param rsvNm5 the value for WEBMD.U700JKUS.RSV_NM5
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setRsvNm5(String rsvNm5) {
        this.rsvNm5 = rsvNm5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.CMN_TANTO_CD
     *
     * @return the value of WEBMD.U700JKUS.CMN_TANTO_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getCmnTantoCd() {
        return cmnTantoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.CMN_TANTO_CD
     *
     * @param cmnTantoCd the value for WEBMD.U700JKUS.CMN_TANTO_CD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setCmnTantoCd(String cmnTantoCd) {
        this.cmnTantoCd = cmnTantoCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.CMN_TERM_ID
     *
     * @return the value of WEBMD.U700JKUS.CMN_TERM_ID
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getCmnTermId() {
        return cmnTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.CMN_TERM_ID
     *
     * @param cmnTermId the value for WEBMD.U700JKUS.CMN_TERM_ID
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setCmnTermId(String cmnTermId) {
        this.cmnTermId = cmnTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.CMN_INSDD
     *
     * @return the value of WEBMD.U700JKUS.CMN_INSDD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getCmnInsdd() {
        return cmnInsdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.CMN_INSDD
     *
     * @param cmnInsdd the value for WEBMD.U700JKUS.CMN_INSDD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setCmnInsdd(String cmnInsdd) {
        this.cmnInsdd = cmnInsdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.CMN_UPDDD
     *
     * @return the value of WEBMD.U700JKUS.CMN_UPDDD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getCmnUpddd() {
        return cmnUpddd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.CMN_UPDDD
     *
     * @param cmnUpddd the value for WEBMD.U700JKUS.CMN_UPDDD
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setCmnUpddd(String cmnUpddd) {
        this.cmnUpddd = cmnUpddd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.CMN_UPDTIME
     *
     * @return the value of WEBMD.U700JKUS.CMN_UPDTIME
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getCmnUpdtime() {
        return cmnUpdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.CMN_UPDTIME
     *
     * @param cmnUpdtime the value for WEBMD.U700JKUS.CMN_UPDTIME
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setCmnUpdtime(String cmnUpdtime) {
        this.cmnUpdtime = cmnUpdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEBMD.U700JKUS.CMN_PROGRAM_ID
     *
     * @return the value of WEBMD.U700JKUS.CMN_PROGRAM_ID
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public String getCmnProgramId() {
        return cmnProgramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEBMD.U700JKUS.CMN_PROGRAM_ID
     *
     * @param cmnProgramId the value for WEBMD.U700JKUS.CMN_PROGRAM_ID
     *
     * @mbggenerated Mon Jun 08 13:53:15 ICT 2015
     */
    public void setCmnProgramId(String cmnProgramId) {
        this.cmnProgramId = cmnProgramId;
    }
}